<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>
<title>Employer Home </title>


	</head>
	
        
     <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
	<tr>
    <td style="padding-left:0px; padding-right:0px;">
	
    <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet4">
        <tr>
        <td width="" valign="top" style="padding-top:30px;">
            
 
	

		</td>
        <td valign="top">
           
		
		
        <!------------------------
		JOBPOSTING STEP 01 STARTS:
		-------------------------->
        <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet4">
			<FORM name="frmJobPostingStep01" id="frmJobPostingStep01" method="post" action=<?php echo$this->escape($this->postjob)?>>
			
				<tr>

				<td class="headLeft">&nbsp;</td>
				<td height="33" colspan="2" class="head">Job Requirements</td>
				<td class="headRight">&nbsp;</td>
				</tr>
				<!--
				JOB CATEGORY:
				-->
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>
				<td>
				
					 Job Category
				 		 
				<img src="images/star.gif" width="7" height="7" hspace="5">
                </td>
				
                <td width="70%">
               	 <?php $datas = $this->category;?> 
				<SELECT name="cboJobCategory" id="cboJobCategory" style="width:230px">
					<!--option value="-1" >Select</option-->
						
							   <!--<option value="" selected></option>-->
						 <option value='-1' Selected>Select</option>
						 <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getCategoryType()?> >    <?php echo$datas[$i]->getCategoryType()?></option>
			
               <?php } ?>

                    <option value="-10" >Others</option>
				</SELECT>
                </td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
				<!--
				JOB TITLE:
				-->            
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>
				<td>

				
					 Job Title
						 
				<img src="images/star.gif" width="7" height="7" hspace="5">				</td>
				<td>
				<INPUT type="text" name="txtJobTitle" id="txtJobTitle" class="BDJtextBox" style="width:90%;" maxlength="100" value="">				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
				<!--
				NO. OF VACANCIES:
				-->            			
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>

				<td>
				
				     No. of Vacancies
						 
				<img src="images/star.gif" width="7" height="7" hspace="5">				</td>
				<td>
				<INPUT name="txtTotalVacancy" type="text" class="BDJtextBox" id="txtTotalVacancy" style="width:10%;" value="" maxlength="50">				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
							
				<!--
				APPLY INSTRUCTIONS
				-->
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>
				<td valign="top" style="padding-top:3px; padding-bottom:2px;">
				
				
				<!--
				APPLICATION DEADLINE
				-->				
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>
				<td>
				
				     Application Deadline
						 
				<img src="images/star.gif" width="7" height="7" hspace="5">				</td>
				<td>
				<SELECT name="cboDay" id="cboDay" style="vertical-align:middle;"> 
					<option value="-1" selected>dd</option>

					
						  <option value="1" >1</option>					      
					
						  <option value="2" >2</option>					      
					
						  <option value="3" >3</option>					      
					
						  <option value="4" >4</option>					      
					
						  <option value="5" >5</option>					      
					
						  <option value="6" >6</option>					      
					
						  <option value="7" >7</option>					      
					
						  <option value="8" >8</option>					      
					
						  <option value="9" >9</option>					      
					
						  <option value="10" >10</option>					      
					
						  <option value="11" >11</option>					      
					
						  <option value="12" >12</option>					      
					
						  <option value="13" >13</option>					      
					
						  <option value="14" >14</option>					      
					
						  <option value="15" >15</option>					      
					
						  <option value="16" >16</option>					      
					
						  <option value="17" >17</option>					      
					
						  <option value="18" >18</option>					      
					
						  <option value="19" >19</option>					      
					
						  <option value="20" >20</option>					      
					
						  <option value="21" >21</option>					      
					
						  <option value="22" >22</option>					      
					
						  <option value="23" >23</option>					      
					
						  <option value="24" >24</option>					      
					
						  <option value="25" >25</option>					      
					
						  <option value="26" >26</option>					      
					
						  <option value="27" >27</option>					      
					
						  <option value="28" >28</option>					      
					
						  <option value="29" >29</option>					      
					
						  <option value="30" >30</option>					      
					
						  <option value="31" >31</option>					      
					
				</SELECT>

				<SELECT name="cboMonth" id="cboMonth" style="vertical-align:middle;">
					<option value="-1" selected>mm</option>
					<option value="01" >Jan</option>
					<option value="02" >Feb</option>
					<option value="03" >Mar</option>
					<option value="04" >Apr</option>

					<option value="05" >May</option>
					<option value="06" >Jun</option>
					<option value="07" >Jul</option>
					<option value="08" >Aug</option>
					<option value="09" >Sep</option>
					<option value="10" >Oct</option>

					<option value="11"  >Nov</option>
					<option value="12" >Dec</option>
				</SELECT>
				
				<SELECT name="cboYear" id="cboYear" style="vertical-align:middle;">
					<option value="-1">yyyy</option>
					<option value="2011" >2011</option>
					<option value="2012" >2012</option>

				</SELECT>
				&nbsp;
				<SPAN class="BDJRedArial11px">
				
				     [Date Format : day-month-year; i.e. 16-Dec-1971]
				
				</SPAN>				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
				<!--
				BILLING CONTACT
				-->							
				<tr class="body">

				<td class="bodyLeft">&nbsp;</td>
				<td>
				
					 Billing Contact
					 
				<img src="images/star.gif" width="7" height="7" hspace="5"></td>
				<td>
				<INPUT name="txtBillingContact" type="text" class="BDJtextBox" id="txtBillingContact" style="width:60%;vertical-align:middle;" value="" maxlength="80">				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
				<!--
				DESIGNATION
				-->							
				<tr class="body">

				<td class="bodyLeft">&nbsp;</td>
				<td>
				
					 Designation
					 
				<img src="images/star.gif" width="7" height="7" hspace="5"></td>
				<td>
				<INPUT name="txtDesignation" type="text" class="BDJtextBox" id="txtDesignation" style="width:60%;" value="" maxlength="80">				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
				<!--
				ALTERNATIVE COMPANY NAME:
				-->

				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>
				<td>In this job do you want to display</td>
				<td style="padding-top:2px; padding-bottom:2px;">
				<SPAN class="BDJGrayArial11px">
				<INPUT type="radio" name="optAliasName" id="optCompanyName" value="0" style="vertical-align:middle;" checked="checked"  onClick="SetAliasName();">
				Company Name
				<INPUT type="radio" name="optAliasName" id="optOtherName" value="1" style="vertical-align:middle;"  onClick="SetAliasName();">
				Other
                </SPAN>				
                </td>

				<td class="bodyRight">&nbsp;</td>
				</tr>
        	
				
				
				<!--
				DO YOU WANT TO HIDE[COMMON FIELD]
				-->
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>

				<td><SPAN id="spnHideCompanyAddress">Do you want to hide Company Address ?</SPAN></td>
				<td style="padding-top:2px; padding-bottom:2px;">
				<SPAN class="BDJGrayArial11px">
                <!--
				<INPUT type="checkbox" name="chkHideCompanyAddress" id="chkHideCompanyAddress" value="1" style="vertical-align:middle;"  checked > 
				Company Address                
                -->
                <input type="radio" name="optHideCompanyAddress" id="optHideCompanyAddress" value="1"  />
                Yes
                <input type="radio" name="optHideCompanyAddress" id="optHideCompanyAddress" value="0"  checked />                
                No
                </SPAN>
				<SCRIPT language="javascript">
					//NOTES: THIS LOGIC HAS BEEN MADE DISABLE AT 13 JUNE 2007.
					//SetHideCompanyAddress();
				</SCRIPT>				</td>

				<td class="bodyRight">&nbsp;</td>
				</tr>
				
				<tr class="body">
				<td class="bodyLeft" style="border-bottom:0px;">&nbsp;</td>
				<td style="border-bottom:0px;" class="bodyRight">&nbsp;</td>
				</tr>	
				
				<!--
		JOB POSTING STEP 02: STARTS
		-->		
    	
					<tr>
            <td class="headLeft">&nbsp;</td>

              <td class="headRight">&nbsp;</td>
            </tr>
			
			<!--
			AGE RANGE [COMMON FIELD]
			-->			
			<tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td width="30%">			
			<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border:0px;">            
				<tr>
				<td style="border:0px;">

				Age Range
				</td>
				<td align="right" style="border:0px;">
				<SPAN class="BDJGrayArial11px">From:</SPAN>&nbsp;
				</td>
                </tr>
			</table>
			</td>
        	<td width="70%">			
			<SELECT name="cboAgeFrom" id="cboAgeFrom" style="vertical-align:middle">

				<option value="-1">Any</option>
				
					  <option value="18" >18</option>
				
					  <option value="19" >19</option>
				
					  <option value="20" >20</option>
				
					  <option value="21" >21</option>
				
					  <option value="22" >22</option>

				
					  <option value="23" >23</option>
				
					  <option value="24" >24</option>
				
					  <option value="25" >25</option>
				
					  <option value="26" >26</option>
				
					  <option value="27" >27</option>
				
					  <option value="28" >28</option>

				
					  <option value="29" >29</option>
				
					  <option value="30" >30</option>
				
					  <option value="31" >31</option>
				
					  <option value="32" >32</option>
				
					  <option value="33" >33</option>
				
					  <option value="34" >34</option>

				
					  <option value="35" >35</option>
				
					  <option value="36" >36</option>
				
					  <option value="37" >37</option>
				
					  <option value="38" >38</option>
				
					  <option value="39" >39</option>
				
					  <option value="40" >40</option>

				
					  <option value="41" >41</option>
				
					  <option value="42" >42</option>
				
					  <option value="43" >43</option>
				
					  <option value="44" >44</option>
				
					  <option value="45" >45</option>
				
					  <option value="46" >46</option>

				
					  <option value="47" >47</option>
				
					  <option value="48" >48</option>
				
					  <option value="49" >49</option>
				
					  <option value="50" >50</option>
				
					  <option value="51" >51</option>
				
					  <option value="52" >52</option>

				
					  <option value="53" >53</option>
				
					  <option value="54" >54</option>
				
					  <option value="55" >55</option>
				
					  <option value="56" >56</option>
				
					  <option value="57" >57</option>
				
					  <option value="58" >58</option>

				
					  <option value="59" >59</option>
				
					  <option value="60" >60</option>
				
					  <option value="61" >61</option>
				
					  <option value="62" >62</option>
				
					  <option value="63" >63</option>
				
					  <option value="64" >64</option>

				
					  <option value="65" >65</option>
				
					  <option value="66" >66</option>
				
					  <option value="67" >67</option>
				
					  <option value="68" >68</option>
				
					  <option value="69" >69</option>
				
					  <option value="70" >70</option>

				
					  <option value="71" >71</option>
				
					  <option value="72" >72</option>
				
					  <option value="73" >73</option>
				
					  <option value="74" >74</option>
				
					  <option value="75" >75</option>
				
					  <option value="76" >76</option>

				
					  <option value="77" >77</option>
				
					  <option value="78" >78</option>
				
					  <option value="79" >79</option>
				
					  <option value="80" >80</option>
				
					  <option value="81" >81</option>
				
					  <option value="82" >82</option>

				
					  <option value="83" >83</option>
				
					  <option value="84" >84</option>
				
					  <option value="85" >85</option>
				
					  <option value="86" >86</option>
				
					  <option value="87" >87</option>
				
					  <option value="88" >88</option>

				
					  <option value="89" >89</option>
				
					  <option value="90" >90</option>
				
			</SELECT>
	    	<SPAN class="BDJGrayArial11px">To:</SPAN>
			<SELECT name="cboAgeTo" id="cboAgeTo" style="vertical-align:middle">
				<option value="-1">Any</option>
				
					  <option value="18" >18</option>

				
					  <option value="19" >19</option>
				
					  <option value="20" >20</option>
				
					  <option value="21" >21</option>
				
					  <option value="22" >22</option>
				
					  <option value="23" >23</option>
				
					  <option value="24" >24</option>

				
					  <option value="25" >25</option>
				
					  <option value="26" >26</option>
				
					  <option value="27" >27</option>
				
					  <option value="28" >28</option>
				
					  <option value="29" >29</option>
				
					  <option value="30" >30</option>

				
					  <option value="31" >31</option>
				
					  <option value="32" >32</option>
				
					  <option value="33" >33</option>
				
					  <option value="34" >34</option>
				
					  <option value="35" >35</option>
				
					  <option value="36" >36</option>

				
					  <option value="37" >37</option>
				
					  <option value="38" >38</option>
				
					  <option value="39" >39</option>
				
					  <option value="40" >40</option>
				
					  <option value="41" >41</option>
				
					  <option value="42" >42</option>

				
					  <option value="43" >43</option>
				
					  <option value="44" >44</option>
				
					  <option value="45" >45</option>
				
					  <option value="46" >46</option>
				
					  <option value="47" >47</option>
				
					  <option value="48" >48</option>

				
					  <option value="49" >49</option>
				
					  <option value="50" >50</option>
				
					  <option value="51" >51</option>
				
					  <option value="52" >52</option>
				
					  <option value="53" >53</option>
				
					  <option value="54" >54</option>

				
					  <option value="55" >55</option>
				
					  <option value="56" >56</option>
				
					  <option value="57" >57</option>
				
					  <option value="58" >58</option>
				
					  <option value="59" >59</option>
				
					  <option value="60" >60</option>

				
					  <option value="61" >61</option>
				
					  <option value="62" >62</option>
				
					  <option value="63" >63</option>
				
					  <option value="64" >64</option>
				
					  <option value="65" >65</option>
				
					  <option value="66" >66</option>

				
					  <option value="67" >67</option>
				
					  <option value="68" >68</option>
				
					  <option value="69" >69</option>
				
					  <option value="70" >70</option>
				
					  <option value="71" >71</option>
				
					  <option value="72" >72</option>

				
					  <option value="73" >73</option>
				
					  <option value="74" >74</option>
				
					  <option value="75" >75</option>
				
					  <option value="76" >76</option>
				
					  <option value="77" >77</option>
				
					  <option value="78" >78</option>

				
					  <option value="79" >79</option>
				
					  <option value="80" >80</option>
				
					  <option value="81" >81</option>
				
					  <option value="82" >82</option>
				
					  <option value="83" >83</option>
				
					  <option value="84" >84</option>

				
					  <option value="85" >85</option>
				
					  <option value="86" >86</option>
				
					  <option value="87" >87</option>
				
					  <option value="88" >88</option>
				
					  <option value="89" >89</option>
				
					  <option value="90" >90</option>

								
			</SELECT>
			<SPAN class="BDJRedArial11px">[Leave this field as it is if don’t want to mention age.]</SPAN>			
			</td>
        	<td class="bodyRight">&nbsp;</td>
        	</tr>			
			
			<!--
			GENDER [COMMON FIELD]
			-->        	
			<tr class="body">
        	<td class="bodyLeft">&nbsp;</td>
        	<td>Gender</td>

        	<td>
			<SPAN class="BDJGrayArial11px">
			<INPUT type="radio" name="optGender" id="optGender" value="M" style="vertical-align:middle;" >
			Male Only	  
			<INPUT type="radio" name="optGender" id="optGender" value="F" style="vertical-align:middle;" >
			Female Only
			<INPUT type="radio" name="optGender" id="optGender" value="B" style="vertical-align:middle;" checked="checked">
			Any 
			</SPAN>
			</td>

        	<td class="bodyRight">&nbsp;</td>
        	</tr>			
			
			<!--
			JOB TYPE [COMMON FIELD]
			-->        	        	
			<tr class="body">
        	<td class="bodyLeft">&nbsp;</td>
        	<td>Job Type</td>
        	<td>
			<SPAN class="BDJGrayArial11px">
        	<INPUT type="radio" name="optJobType" id="optJobType" value="FullTime" style="vertical-align:middle;"  checked="checked" >

        	Full Time
			<INPUT type="radio" name="optJobType" id="optJobType" value="PartTime" style="vertical-align:middle;" >
        	Part Time
        	<INPUT type="radio" name="optJobType" id="optJobType" value="Contract" style="vertical-align:middle;" >
        	Contract
			</SPAN>
			</td>
        	<td class="bodyRight">&nbsp;</td>
        	</tr>
						
			
					
			<!--
			EDUCATIONAL QUALIFICATION [COMMON FIELD]
			-->              
	        <tr class="body">
    	    <td class="bodyLeft">&nbsp;</td>

	        <td valign="top" style="padding-top:3px; padding-bottom:2px;">
			
				 Educational Qualification
					 
			<img src="images/star.gif" width="7" height="7" hspace="5">
			</td>
	        <td style="padding-top:2px; padding-bottom:2px;">
			<TEXTAREA name="txtEducation" id="txtEducation" class="BDJtextBox" onKeyUp="countLetter(this.id , 500 , 'CADD_sp1' , 'Educational Qualification' , 1)" onChange="countLetter(this.id , 500 , 'CADD_sp1' , 'Educational Qualification' , 1 )" style="width:100%; height:80px;"></TEXTAREA>
			<SPAN id="CADD_sp1" name="CADD_sp1" class="BDJValues"></SPAN>
			</td>
	        <td class="bodyRight">&nbsp;</td>

	        </tr>
			
			<!--
			JOB DESCRIPTION[COMMON FIELD]
			-->                      				
			<tr class="body">			
        	<td class="bodyLeft">&nbsp;</td>
	        <td valign="top" style="padding-top:3px;">			
			
				 Job Description/Responsibility
				 
			<img src="images/star.gif" width="7" height="7" hspace="5">
			</td>
			
	        <td style="padding-top:2px; padding-bottom:2px;">
	        <TEXTAREA name="txtJobDescription" id="txtJobDescription" class="BDJtextBox" style="width:100%; height:80px;"></TEXTAREA>

			</td>
    	    <td class="bodyRight">&nbsp;</td>
        	</tr>
			
			<!--
			ADDITIONAL JOB REQUIREMENTS [COMMON FIELD]
			-->        
			<tr class="body">
			<td class="bodyLeft">&nbsp;</td>
			<td valign="top" style="padding-top:3px;">
			
			     Additional Job Requirements
			
			<img src="images/star.gif" width="7" height="7" hspace="5">
			</td>

			<td style="padding-top:2px; padding-bottom:2px;">
			<TEXTAREA name="txtJobRequirements" id="txtJobRequirements" class="BDJtextBox" style="width:100%; height:80px;"></TEXTAREA>
			</td>
			<td class="bodyRight">&nbsp;</td>
			</tr>
				    	    <td class="bodyRight">&nbsp;</td>
	        </tr>
						
			<tr class="body">
        	<td class="bodyLeft">&nbsp;</td>
        	<td>			
					
			<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border:0px;">
        		<tr>
            	<td style="border:0px;">
				
					 <SPAN id="spnExperienceYear" style="color:#226EC7">Total Years of Experience</SPAN>

				
				</td>
            	<td align="right" style="border:0px;"><SPAN class="BDJGrayArial11px" id="spnExperienceFrom" style="color:#535A62">Min</SPAN>:&nbsp;</td>
            	</tr>
        	</table>
			</td>
        	<td>
			<SELECT name="cboExperienceFrom" id="cboExperienceFrom" style="vertical-align:middle" >
				<option value="-1">Any</option>

									
					  <option value="0" >0</option>
									
					  <option value="1" >1</option>
									
					  <option value="2" >2</option>
									
					  <option value="3" >3</option>
									
					  <option value="4" >4</option>
									
					  <option value="5" >5</option>

									
					  <option value="6" >6</option>
									
					  <option value="7" >7</option>
									
					  <option value="8" >8</option>
									
					  <option value="9" >9</option>
									
					  <option value="10" >10</option>
									
					  <option value="11" >11</option>

									
					  <option value="12" >12</option>
									
					  <option value="13" >13</option>
									
					  <option value="14" >14</option>
									
					  <option value="15" >15</option>
									
					  <option value="16" >16</option>
									
					  <option value="17" >17</option>

									
					  <option value="18" >18</option>
									
					  <option value="19" >19</option>
									
					  <option value="20" >20</option>
									
					  <option value="21" >21</option>
									
					  <option value="22" >22</option>
									
					  <option value="23" >23</option>

									
					  <option value="24" >24</option>
									
					  <option value="25" >25</option>
									
					  <option value="26" >26</option>
									
					  <option value="27" >27</option>
									
					  <option value="28" >28</option>
									
					  <option value="29" >29</option>

									
					  <option value="30" >30</option>
									
					  <option value="31" >31</option>
									
					  <option value="32" >32</option>
									
					  <option value="33" >33</option>
									
					  <option value="34" >34</option>
									
					  <option value="35" >35</option>

									
					  <option value="36" >36</option>
									
					  <option value="37" >37</option>
									
					  <option value="38" >38</option>
									
					  <option value="39" >39</option>
									
					  <option value="40" >40</option>
									
					  <option value="41" >41</option>

									
					  <option value="42" >42</option>
									
					  <option value="43" >43</option>
									
					  <option value="44" >44</option>
									
					  <option value="45" >45</option>
									
					  <option value="46" >46</option>
									
					  <option value="47" >47</option>

									
					  <option value="48" >48</option>
									
					  <option value="49" >49</option>
									
					  <option value="50" >50</option>
							
    		</SELECT>
        	<SPAN class="BDJGrayArial11px" id="spnExperienceTo" style="color:#535A62">
			Max:
			<SELECT name="cboExperienceTo" id="cboExperienceTo" style="vertical-align:middle" >
				<option value="-1">Any</option>

				
					  <option value="1" >1</option>
				
					  <option value="2" >2</option>
				
					  <option value="3" >3</option>
				
					  <option value="4" >4</option>
				
					  <option value="5" >5</option>
				
					  <option value="6" >6</option>

				
					  <option value="7" >7</option>
				
					  <option value="8" >8</option>
				
					  <option value="9" >9</option>
				
					  <option value="10" >10</option>
				
					  <option value="11" >11</option>
				
					  <option value="12" >12</option>

				
					  <option value="13" >13</option>
				
					  <option value="14" >14</option>
				
					  <option value="15" >15</option>
				
					  <option value="16" >16</option>
				
					  <option value="17" >17</option>
				
					  <option value="18" >18</option>

				
					  <option value="19" >19</option>
				
					  <option value="20" >20</option>
				
					  <option value="21" >21</option>
				
					  <option value="22" >22</option>
				
					  <option value="23" >23</option>
				
					  <option value="24" >24</option>

				
					  <option value="25" >25</option>
				
					  <option value="26" >26</option>
				
					  <option value="27" >27</option>
				
					  <option value="28" >28</option>
				
					  <option value="29" >29</option>
				
					  <option value="30" >30</option>

				
					  <option value="31" >31</option>
				
					  <option value="32" >32</option>
				
					  <option value="33" >33</option>
				
					  <option value="34" >34</option>
				
					  <option value="35" >35</option>
				
					  <option value="36" >36</option>

				
					  <option value="37" >37</option>
				
					  <option value="38" >38</option>
				
					  <option value="39" >39</option>
				
					  <option value="40" >40</option>
				
					  <option value="41" >41</option>
				
					  <option value="42" >42</option>

				
					  <option value="43" >43</option>
				
					  <option value="44" >44</option>
				
					  <option value="45" >45</option>
				
					  <option value="46" >46</option>
				
					  <option value="47" >47</option>
				
					  <option value="48" >48</option>

				
					  <option value="49" >49</option>
				
					  <option value="50" >50</option>
				
	  		</SELECT>
        	year(s)
			</SPAN>
			</td>
        	<td class="bodyRight">&nbsp;</td>
        	</tr>
							<!--
			PREFERRED SALARY RANGE [COMMON FIELD]
			-->
			<tr class="body">
			<td class="bodyLeft" style="border-bottom:0px;">&nbsp;</td>
			<td style="border:0px; padding-top:5px;" valign="top">Compensation and other benefits</td>
			<td style="padding-top:5px; padding-bottom:2px; padding-left:5px; border:0px;">
			
			<SPAN class="BDJGrayArial11px" 
				  style="color:
									   #535A62
									"
								id="spnMinimumSalary">Minimum&nbsp;</SPAN>
			<INPUT type="text" 
				   name="txtSalaryFrom" 
				   id="txtSalaryFrom" 
				   class="BDJtextBox"
				  maxlength="10" 				   
				   value="" 
				   
				   style="width:20%;vertical-align:middle;">
			<SPAN class="BDJGrayArial11px" 
			      style="color:
									   #535A62
									" 
								id="spnMaximumSalary" >Maximum&nbsp;</SPAN>
			<INPUT type="text" 
				   name="txtSalaryTo" 
				   id="txtSalaryTo" 
				  
				   maxlength="10"
				   class="BDJtextBox" 				   
				   value="" 
				   
					style="width:20%;vertical-align:middle;" >
			<SPAN  id="spnBDT" 
			       class="BDJGrayArial11px" 
				   style="color:
									    #535A62
									 ">monthly In Krs</SPAN>
			<BR><BR>
			<SPAN class="BDJGrayArial11px">Other Benefits</SPAN>

			<TEXTAREA name="txtOtherBenefits" id="txtOtherBenefits" class="BDJtextBox" style="width:100%; height:80px;"></TEXTAREA>			
			</td>
			<td class="bodyRight" style="border-bottom:0px;">&nbsp;</td>
			</tr>		
				<!--END-->  
				<tr class="body">

				<td class="bodyLeft">&nbsp;</td>
				<td colspan="2" align="center" style="height:50px;">
				<INPUT type="submit" name="post" value ="Post Job" width="109" height="21">
				
				<td class="bodyRight">&nbsp;</td>
				</tr>
				
				
			</FORM>
        </table>

        </td>
        </tr>
        </table>
        </td>
        </tr>
        </table>
        
     
            
            
     