

<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>


<title>Employer Home </title>


	</head>
	
        
     <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
	<tr>
    <td style="padding-left:20px; padding-right:20px;">
	
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
        <td width="215" valign="top" style="padding-top:30px;">
            
 
	

		</td>
        <td valign="top">
             
				
    <table width="350" border="0" align="center" cellspacing="0" cellpadding="0" id="tblSet1">
    <tr>
    <td class="headLeft">&nbsp;</td>
    <td class="head">&nbsp;&nbsp; Congratulation !  </td>

    <td class="headRight">&nbsp;</td>
    </tr>
            
    <tr class="body">
    <td class="bodyLeft">&nbsp;</td>
    <td  style="height:100px; padding-left:15px;font-size:12px;" align="center" valign="middle">
        You have successfully posted your job vacancy.<br/>Your posted job will be available at portalJobsshortly.<br/><br/><a href=<?php echo$this->escape($this->viewpostjob)?> style='text-decoration:none'>Click to View this Job</a> &nbsp;|&nbsp; <a href=<?php echo$this->escape($this->postjob)?> style='text-decoration:none'>Post Another Job</a><br/><br/>

    </td>
    <td class="bodyRight">&nbsp;</td>
    </tr>
            
    <tr>
    <td height="5" class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
    <td class="footerMiddle"><img src="images/pix.gif" width="1" height="1"></td>
    <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
    </tr>
    </table>
       <br />
        
   
       
       
        </table>

        </td>
        </tr>
        </table>
       
 