<?php

$actionhelper = Zend_Controller_Action_HelperBroker::getExistingHelper('CustomActionHelper');

$role = $actionhelper->getRole();

$sidebarmenu = array();
if($role==APP_Authorization_Roles::GUEST)
{
   // array_push($sidebarmenu, array('profile','create','Create Profile'));
   // array_push($sidebarmenu, array('profile','create',' '));
}
else if($role == APP_Authorization_Roles::EMPLOYEE)
{
    array_push($sidebarmenu, array('resume','edit','Edit Resume'));
    array_push($sidebarmenu, array('resume','view','View Resume'));
    array_push($sidebarmenu, array('resume','email','Email Resume'));
    array_push($sidebarmenu, array('resume','delete','Delete Resume'));
    array_push($sidebarmenu, array('employer','block','Block Employer'));
    array_push($sidebarmenu, array('view','stats','View Stats'));
    array_push($sidebarmenu, array('notification','email','Email Notification'));
    array_push($sidebarmenu, array('change','password','Change Password'));
}
else if($role == APP_Authorization_Roles::EMPLOYER)
{
    array_push($sidebarmenu, array('jobpost','postform','Post Job'));
    array_push($sidebarmenu, array('searchcv','index','Search CV'));
    array_push($sidebarmenu, array('servcecharge','index','Service Charges'));
    array_push($sidebarmenu, array('change','password','Change Password'));
}
else if($role == APP_Authorization_Roles::ADMIN)
{


}

$format = "<a href='%s'>%s</a><br/>";
$basepath = Zend_Controller_Front::getInstance()->getBaseUrl();

foreach($sidebarmenu as $menus)
{
    printf($format, $basepath . "/" . $menus[0] . "/" . $menus[1] , $menus[2]);
}

?>
