<title>Employer Home </title>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>
	</head>
	<body id="sys_background">
		<div id="outer">
			<div id="sys_banner" >


				<h1><a id="sys_heading" href="./">Employer Home</a></h1>
			</div>
			<div id="menu">
				<ul class='sys_navigation'>



												<li class="first"><a href=<?=$this->escape($this->home)?> title="Home">Home</a></li>
                                                    	<li><a href=<?=$this->escape($this->postjob)?> title="Post Job">Post Job</a></li>

                                                        <li><a href=<?=$this->escape($this->searchcv)?> title="Search Cv">Search CV</a></li>


													<li><a href=<?=$this->escape($this->servicecharge)?> title="Service Charge">Service charge</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Menu">Service Benifits</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Contacts">Contacts</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Other">Other</a></li>





													


													








									</ul>
			</div>
			<div id="content">
				    <div style="width: 100%; padding: 0px; margin: 0px" class="layout_1-column">

        <div id="layout_row1">
        
        
 <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:20px; padding-right:20px;"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #FFFFFF;">
        <tr>
          <td width="215" height="30" align="center"><img src="images/txt_corporate_panel.gif" width="161" height="14"></td>
          <td style="background-image:url(images/gradient_top.jpg); background-repeat:repeat-y;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="BDJCompanyName" >&nbsp;&nbsp;Company Name: <?=$this->escape($this->company)?></td>

                <td align="right"><img src="images/icons_logout2.gif" width="16" height="15" hspace="5" align="middle"><a href="logout.asp" class="BDJGreenArial11px"><strong>Logout</strong></a></td>
            </tr>
          </table></td>
        </tr>
      </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="215" height="515" valign="top" style="padding-top:30px;">
    
    <table width="190" border="0" cellspacing="0" cellpadding="0" id="tblSet2">
        <tr>
        <td class="headLeft"></td>
        <td class="headMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
        <td class="headRight"></td>
        </tr>
        
        <tr>
        <td class="bodyLeft"><img src="images/pix.gif" width="1" height="1" /></td>
        <td valign="top" class="body" style="padding:5px;"><span class="BDJFormTitle">Main Menu</span><br>

        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>
        
        <div class="BDJWelcomeTxt">
         <img src="images/icons_addnew.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?=$this->escape($this->postform)?> class='BDJNavLink'>Post a New Job</a><br>
        <img src="images/icons_account.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?=$this->escape($this->findemployer)?> class='BDJNavLink'>Edit Account Info</a><br>
        <img src="images/icons_invoice.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?=$this->escape($this->create)?> class='BDJNavLink'>Payment Status</a><br>  
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?=$this->escape($this->create)?> class='BDJNavLink'>Contact Support</a><br>

        <img src="images/btn_icon_login.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?=$this->escape($this->create)?> class='BDJNavLink'>Change Password</a><br>
        
        <!--
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>                      
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>
        -->
        

        </div>
        
        <img src="images/icons_logout.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href='logout.asp' class='BDJNavLink'>Logout</a><br>
        
        
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>
        <span class="BDJFormTitle">Account Status</span><br>
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
            
            <td class="BDJGrayArial12px">Online Job Posting<br>

            <img src="images/pix.gif" width="50" height="10"><br>
            CV Database Access</td>
            
    
            <td width="30" align="right" class="BDJNoticeVerdana11Red"><strong>						
            No&nbsp;<br>
            <img src="images/pix.gif" width="30" height="10"><br>
            No&nbsp;</strong></td>
            </tr>
        </table>

        
        
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"/><br/><span class="BDJFormTitle">Corporate Support</span><br/>
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"/>
       
       
        <br/>
        <span class="BDJtabLinkSelected">Help Desk:</span> <br/><span class="BDJGrayArial12px"><strong>9117179, 9140345, 01811410858, 01811410860</strong></span>
        <div  style="margin-top:5px;" align="justify" class="BDJRedArial11px">Please call us if you face any difficulty in accessing the online services or plan for subscribing to additional services</div>
        <div class="BDJWelcomeTxt"></div>

        </td>    
        <td class="bodyRight"><img src="images/pix.gif" width="1" height="1" /></td>
        </tr>
        
        <tr>
        <td class="footerLeft"></td>
        <td class="footerMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
        <td class="footerRight"></td>
        </tr>    
    </table>
	<script type="text/JavaScript">qm_create(0,true)</script>

</td>
          <td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td height="30" class="BDJGrayArial12px">Total posted jobs : 0</td>
                <td align="right" class="BDJGrayArial12px">Total number of CVs 
                  available 0</td>
            </tr>
          </table>
	
	  
            <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet1">

              <tr> 
                <td width="6" class="headLeft">&nbsp;</td>
                <td width="28" align="center" class="head">SN</td>
                <td width="144" class="head">Job Title</td>
                <td width="24" class="head">&nbsp;<br> </td>
                <td width="60" class="head">Post Date</td>
                <td width="50" align="center" class="head">Deadline</td>

                
				     <td width="48" align="center" class="head">Edit</td>
                     
                <td width="36" align="center" class="head">Delete</td>
                <td width="50" align="center" class="head">Applied</td>
                <td width="54" align="center" class="head">Viewed </td>
                <td width="61" align="center" class="head">Not Viewed</td>
                <td width="50" align="center" class="head">Shortlisted</td>

                <td width="13" class="headRight">&nbsp;</td>
              </tr>
              <? $edit = $this->editpost;?>
               <? $delete = $this->deletepost;?> 
               <? $detail = $this->detailpost;?> 
               <? $datas = $this->postjoblist;?> 
               <?for($i = 0; $i < count($datas);$i++){ ?> 
               
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td align="center" valign="middle">&nbsp; </td>
				<td align="center" valign="middle"> <a href="<?=$detail?>/id/<?=$datas[$i]->getJobID()?> "> <?=$datas[$i]->getJobTitle()?></a></td>
               
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle"><?=$datas[$i]->getJobPostDate()?></td>

                  <td align="center" valign="middle"><?=$datas[$i]->getApplicationDeadline()?></td>

				<td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?=$edit?>/edi/<?=$datas[$i]->getJobID()?>">Edit</a></td>
				 
               				 <td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?=$delete?>/del/<?=$datas[$i]->getJobID()?>">Delete</a></td>
				 
                <td align="center" valign="middle">-</td>
                <td align="center" valign="middle">-</td>
                <td align="center" valign="middle">-</td>

                <td align="center" valign="middle">-</td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
               <? } ?>
              <tr> 
                <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
                <td colspan="11" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"  /></td>
                <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
              </tr>
            </table>

		
         <div class="BDJInstruction2">
			<strong><u></u></strong>
<br/>
<br/>
            <br/>
           </div>	          
		 	
              <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet1">
                  <tr>
                  <td class="headLeft">&nbsp;</td>
                  <td colspan="2" class="head">Pricing Policy of portaljobsOnline Recruitment Services  </td>
                  <td class="headRight">&nbsp;</td>
                  </tr>

                  <tr class="body">
                  <td class="bodyLeft">&nbsp;</td>
                  <td valign="top" nowrap class="bodyCell">
                  <strong>Online Job Posting</strong> at <br>
                  Classified/Category Job section
                  </td>
                  
                  <td valign="top" style="padding:5px;">                  
                  
                       <strong>2000Kr for each job position</strong>   
                  
                  </td>

                  <td class="bodyRight">&nbsp;</td>
                  </tr>
              
                  <tr class="body">
                  <td class="bodyLeft">&nbsp;</td>
                  <td valign="top" nowrap class="bodyCell">
                  <strong>Hot Jobs Announcement Service</strong> at <br>
                  Your company logo and position name 
            
                 
                  <br />
                  linked with custom designed web page
                  <br />
                  for your job announcements
                  </td>
                  <td valign="top"  style="padding:5px;"> 		
                  
                  	  <strong>3000Kr for each job position</strong>   
                     
                  
				  </td>
              	  <td class="bodyRight">&nbsp;</td>

		          </tr>
                  
                  <tr class="body">
                  <td class="bodyLeft">&nbsp;</td>
                  <td valign="top" nowrap class="bodyCell"><strong>Online CV Database</strong> Access </td>
                  <td valign="top"  style="padding:5px;">
                  
                       <strong>3000 for one year</strong>
                       <br/>Fee for Online CV Database access has to be paid in advance.
                  
                  </td>

                  <td class="bodyRight">&nbsp;</td>
                  </tr>
                 
                  
                  <tr class="body">
                  <td class="bodyLeft">&nbsp;</td>
                  <td valign="top" style="padding:5px;">
                    <p>

                           
                  	   &nbsp;
                    
                    </p>
                    <!--<p align="right"><font color='#009933' face='Verdana' size='1'><BLINK>New Pricing will be effective from october 01, 2010</BLINK></font></p>-->
                    </td>
              	  <td class="bodyRight">&nbsp;</td>
            	  </tr>
                  
                  
                  
                  <tr>
                  <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
                  <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"  /></td>

                  <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
                  </tr>
          	   </table>
		  
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>

    <td height="50" align="center" valign="bottom" class="BDJCopyright"></td>
  </tr>
</table>

 
       

        
     
            
            
            
        </div>
    </div>
			</div>
            <div id="footer-wrap">
			<div id='sys_footer' class='sys_footer'>Designed by <a href='http://www.freecsstemplates.org' target='_blank'>XXXXXXXXXXX</a></div>




            </div>
        </div>
    </body>