<title>Employer Home </title>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>
	</head>
	
        
 <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:0px; padding-right:0px;">
   
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="0" height="515" valign="top" style="padding-top:30px;">
    
    
	<script type="text/JavaScript">qm_create(0,true)</script>

</td>
          <td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td height="30" class="BDJGrayArial12px">Total posted jobs : 0</td>
                <td align="right" class="BDJGrayArial12px">Total number of CVs 
                  available 0</td>
            </tr>
          </table>
	
	  
            <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet4">

              <tr> 
                <td width="6" class="headLeft">&nbsp;</td>
                <td width="28" align="center" class="head">SN</td>
                <td width="144" class="head">Job Title</td>
                <td width="24" class="head">&nbsp;<br> </td>
                <td width="60" class="head">Post Date</td>
                <td width="50" align="center" class="head">Deadline</td>

                
				     <td width="48" align="center" class="head">Edit</td>
                     
                <td width="36" align="center" class="head">Delete</td>
                <td width="50" align="center" class="head">Applied</td>
                <td width="4" align="center" class="head"> </td>
                <td width="4" align="center" class="head"></td>
                <td width="4" align="center" class="head"></td>

                <td width="13" class="headRight">&nbsp;</td>
              </tr>
              <?php   $edit = $this->editpost;?>
               <?php   $delete = $this->deletepost;?> 
               <?php   $detail = $this->detailpost;?> 
               <?php   $datas = $this->postjoblist;?> 
                <?php for($i = 0; $i < count($datas);$i++){ ?> 
               
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td align="center" valign="middle">&nbsp; </td>
				<td align="center" valign="middle"> <a href="<?php echo$detail?>/id/<?php echo$datas[$i]->getJobID()?> "> <?php echo$datas[$i]->getJobTitle()?></a></td>
               
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle"><?php echo$datas[$i]->getJobPostDate()?></td>

                  <td align="center" valign="middle"><?php echo$datas[$i]->getApplicationDeadline()?></td>

				<td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?php echo$edit?>/edi/<?php echo$datas[$i]->getJobID()?>">Edit</a></td>
				 
               				 <td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?php echo$delete?>/del/<?php echo$datas[$i]->getJobID()?>">Delete</a></td>
				 
                <td align="center" valign="middle">-</td>
                <td align="center" valign="middle">-</td>
                <td align="center" valign="middle">-</td>

                <td align="center" valign="middle">-</td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
               <?php   } ?>
              <tr> 
                <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
                <td colspan="11" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"  /></td>
                <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
              </tr>
            </table>

		
         <div class="BDJInstruction2">
			<strong><u></u></strong>
<br/>
<br/>
            <br/>
           </div>	          
		 	
              <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet1">
                  <tr>
                  <td class="headLeft">&nbsp;</td>
                  <td colspan="2" class="head">Pricing Policy of portaljobsOnline Recruitment Services  </td>
                  <td class="headRight">&nbsp;</td>
                  </tr>

                  <tr class="body">
                  <td class="bodyLeft">&nbsp;</td>
                  <td valign="top" nowrap class="bodyCell">
                  <strong>Online Job Posting</strong> at <br>
                  Classified/Category Job section
                  </td>
                  
                  <td valign="top" style="padding:5px;">                  
                  
                       <strong>2000Kr for job position</strong>   
                  
                  </td>

                  <td class="bodyRight">&nbsp;</td>
                  </tr>
              
                  <tr class="body">
                  <td class="bodyLeft">&nbsp;</td>
                  <td valign="top" nowrap class="bodyCell">
                  <strong>Hot Jobs Announcement Service</strong> at <br>
                  Your company logo and position name 
            
                 
                  <br />
                  
                  
                  along with  your job announcements displyed.
                  </td>
                  <td valign="top"  style="padding:5px;"> 		
                  
                  	  <strong>3000Kr for job position</strong>   
                     
                  
				  </td>
              	  <td class="bodyRight">&nbsp;</td>

		          </tr>
                  
                  <tr class="body">
                  <td class="bodyLeft">&nbsp;</td>
                  <td valign="top" nowrap class="bodyCell"><strong>Online CV Database</strong> Access </td>
                  <td valign="top"  style="padding:5px;">
                  
                       <strong>3000 for one year</strong>
                       <br/>Fee for Online CV Database access has to be paid in advance.
                  
                  </td>

                  <td class="bodyRight">&nbsp;</td>
                  </tr>
                 
                  
                  <tr class="body">
                  <td class="bodyLeft">&nbsp;</td>
                  <td valign="top" style="padding:5px;">
                    <p>

                           
                  	   &nbsp;
                    
                    </p>
                    <!--<p align="right"><font color='#009933' face='Verdana' size='1'><BLINK>New Pricing will be effective from october 01, 2010</BLINK></font></p>-->
                    </td>
              	  <td class="bodyRight">&nbsp;</td>
            	  </tr>
                  
                  
                  
                  <tr>
                  <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
                  <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"  /></td>

                  <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
                  </tr>
          	   </table>
		  
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>

    <td height="50" align="center" valign="bottom" class="BDJCopyright"></td>
  </tr>
</table>

 
       

        