<div id="viewresume">
    <?php
          $this->title ="View Resume";
          $this->headTitle($this->title);
        echo
          '
              <table border="1" cellspacing="1" cellpadding="3">';
                $format = "<tr class = 'header'><td>%s: </td><td class = 'value'>%s</td></tr>";
                foreach($this->view as $abc => $def){
                    foreach($def as $d=>$e){
                        printf($format,$d,$e);
                    }
                }
          echo '</table>'
    ?>
        <img src="<?php echo $this->imagepath ?>"/> 
</div>
