
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>

<title>Employer Home </title>


	</head>

        
    
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:0px; padding-right:0px;">
    
      
        
        <td width="600" valign="top"> 
       
        <form name="frmCorporateNewAccount" id="frmCorporateNewAccount" method="post" action=<?php echo$this->escape($this->action)?> onsubmit="return IsPageValid();"> <!--onsubmit="return IsPageValid();"-->
        <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #FFFFFF;">
        	<tr>
            <td height="30" class="BDJGrayArial12px">&nbsp;</td>
            <td align="right" class="BDJGrayArial12px">Fields marked by <img src="images/star.gif" width="7" height="7" hspace="1"> are mandatory</td>

            </tr>		
         </table>

		
        
        
        <!--
         COMPANY DETAILS:
         -->
         
         <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
            <tr>
            <td class="headLeft">&nbsp;</td>
            <td height="33" colspan="2" class="head"> 
            <?php $vlaues =$this->username;?>       
             Company Details</td>
            <td class="headRight">&nbsp;</td>
            </tr>

                        <!--COMPANY NAME:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td width="30%">Company Name <?php echo$this->escape($vlaues->getCompanyname())?> </td>
            <td width="70%" style="color:#333333">
           
            <input type="hidden" name="txtCompanyName" id="txtCompanyName" maxlength="120" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getCompanyname())?>  />
            <input type="hidden" name="txtPageType" id="txtPageType" value="Update"/>
            </td>

            <td class="bodyRight">&nbsp;</td>
            </tr>
        
            <!--ALTERNATIVE COMPANY NAME:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td>Alternative Company Name</td>
            <td>
            <input type="text" name="txtAliasName" id="txtAliasName" maxlength="50" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getAlternativeCompany())?> />

            <span class="BDJGrayArial12px" style="font-size:9px">N.B</span>
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
                
            <!--CONTACT PERSON:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td>Contact Person<img src="images/star.gif" width="7" height="7" hspace="5"></td>

            <td>
            <input type="text" name="txtContactPerson" id="txtContactPerson" maxlength="100" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getContactperson())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>

            <!--CONTACT PERSON's DESIGNATION:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>

            <td>Contact Person's Designation<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtDesignation" id="txtDesignation" maxlength="100" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getContactPersonDesignation())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
    
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>

            <td align="right" valign="top" style="padding-right:5px;"><span class="BDJGrayArial12px" style="font-size:9px">N.B.</span></td>
            <td style="padding-bottom:2px;">
            <span class="BDJGrayArial12px" style="font-size:11px">
            </span>

            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>

            <tr>
            <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
            <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
            <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
            </tr>		
         </table>

            
         <!--
         BUSINESS TYPE:
         -->
         <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
            <tr>
            <td class="headLeft">&nbsp;</td>
            <td height="33" colspan="2" class="head">Business Type</td>
            <td class="headRight">&nbsp;</td>
            </tr>
            
            <!--BUSINESS TYPES:-->
            <tr class="body">

            <td class="bodyLeft">&nbsp;</td>
            <td width="30%">Business Type<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td width="70%">	
            <?php $datas = $this->businessType;?> 				
            <select name="cboBusinessType"  id="cboBusinessType"  style="width:80%;">
                <option value="-1">Select</option>
                
              <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getBusinessType()?><?php if($datas[$i]->getBusinessType() == $this->escape($vlaues->getBusinessType())) echo ' selected'; ?> > 
                <?php echo$datas[$i]->getBusinessType()?></option>
			
               <?php } ?>
                     
                     <option value="-10" >Others</option>
                
            </select>
            </td>
            <td class="bodyRight">&nbsp;</td>

            </tr>
            
            <!--BUSINESS DESCRIPTION:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td valign="top" style="padding-top:3px; padding-bottom:2px;">Business Description</td>
            <td style="padding-bottom:2px;">
            <textarea name="txtDescription" id="txtDescription" class="BDJtextBox" style="width:80%; height:80px;"></textarea>
            </td>

            <td class="bodyRight">&nbsp;</td>
            </tr>
        
            <tr>
            <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
            <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
            <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
            </tr>		
         </table>
         
         <!--
         PRIMARY CONTACT DETAILS:
         -->

         <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
            <tr>
            <td class="headLeft">&nbsp;</td>
            <td height="33" colspan="2" class="head">Primary Contact Details</td>
            <td class="headRight">&nbsp;</td>
            </tr>
        
            <!--COMPANY ADDRESS:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>

            <td width="30%">Company Address<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td width="70%">
            <input type="text" name="txtCompanyAddress" id="txtCompanyAddress" maxlength="300" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getCompanyAddress())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
                            
            <!--COUNTRY:-->
            <tr class="body">

            <td class="bodyLeft">&nbsp;</td>
            <td>Country<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td>
             <?php $datas = $this->country;?> 
            <select name="cboCountry" id="cboCountry"  style="width:150px;"  onchange="PopulateCity(this.value);GetLocationList(this.value);">
                <option value="-1" selected="selected">Select</option>
                								      
                           <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getCountryName()?> <?php if($datas[$i]->getCountryName() == $this->escape($vlaues->getCountry())) echo ' selected'; ?>>  
               <?php echo$datas[$i]->getCountryName()?></option>
			
               <?php } ?>
                     								      
                                                		
            </select>		
            </td>

            <td class="bodyRight">&nbsp;</td>
            </tr>

            <!--CITY:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>City<img src="images/star.gif" width="7" height="7" hspace="5"></td>        
        <td id="tdCity">        
         <?php $datas = $this->city;?> 
             <select name="cboCity"  id="cboCity" style="width:150px;">
             	<option value="-1" selected="selected">Select</option>
                   <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getCityId()?>  <?php if($datas[$i]->getCityId() == $this->escape($vlaues->getCityId())) echo ' selected'; ?>> 
                <?php echo$datas[$i]->getCityName()?></option>
			
               <?php } ?>
			     					  
             </select>
        
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--CITY:-->
            <!--Area:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td id="tdAreaCaption">Area</td>        
            <td id="tdAreaControl">

              
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
        
            <!--BILLING ADDRESS:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>

            <td>Billing Address<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtBillingAddress" id="txtBillingAddress" maxlength="150" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getBillingAddress())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
    
            <!--CONTACT PHONE:-->
            <tr class="body">

            <td class="bodyLeft">&nbsp;</td>
            <td>Contact Phone<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtContactPhone" id="txtContactPhone" maxlength="30" size="50" class="BDJtextBox" style="width:50%;" value=
<?php echo$this->escape($vlaues->getContactPhone())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>

            <!--CONTACT EMAIL:-->

            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td>Contact E-Mail<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtEmail" id="txtEmail" maxlength="40" size="50" class="BDJtextBox" style="width:50%;" value=<?php echo$this->escape($vlaues->getContactMail())?> />
           
            <span class="BDJRedArial11px">[Do not type more then 1 e-mail address.]</span>
            </td>

            <td class="bodyRight">&nbsp;</td>
            </tr>

            <!--WEBSITE ADDRESS (URL):-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td>Website Address (URL)</td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtURL" id="txtURL" maxlength="50" size="50" class="BDJtextBox" style="width:50%;" value="<?php echo$this->escape($vlaues->getWebsiteAddress())?>" />

            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
            
            <tr>
            <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
            <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
            <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
            </tr>		
         </table>

        <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" style="margin-top:2px;">
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td colspan="2" align="center" style="height:50px;">
            <input type="submit" name="edit" value="Edit Employer" width="109" height="21" />
            <input type="hidden" name="txtuserID" id="txtuserID" value=<?php echo$this->escape($vlaues->getUserId())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>

        </table>			
    	</form>
        <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
            <td style="padding-left:20px; padding-right:20px;"></td>
            </tr>
            <tr>
            <td height="6" align="center" valign="top" class="BDJCopyright"></td>
            </tr>	
        </table>	
        

        </td>
        </tr>
        </table>
        
     
            
            
            
       