<!--<head>

<title>Employer Home </title>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>

</head>

 <table width="60%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:15px; padding-right:15px; padding-top:34px;">
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
        
        
       
        <tr>
          <td rowspan="5" align="center" valign="top"> 
            ### Form table start ###
            <FORM name="frmDefault" id="frmDefault" method="post" action= <?php echo$this->escape($this->login)?> > https://bdjobs.sslcert11.com/corporate/corporate_submit.asp

              <table width="90%" border="0" cellspacing="0" cellpadding="0" id="tblSet2">
                <tr> 
                  <td class="headLeft"></td>
                  <td class="headMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
                  <td class="headRight"></td>
                </tr>
                <tr> 
                  <td class="bodyLeft"><img src="images/pix.gif" width="1" height="1" /></td>
                  <td class="body" style="padding:5px;"><div class="BDJWelcomeTxt">Welcome 
                      to the section for Employers at portaljobs Log into your 
                      Account to get the following online recruitment services:<br>

                      &nbsp;</div>
                    <div align="center"><img src="images/pix_orange.gif" width="6" height="6" hspace="5" style="vertical-align:middle"><span class="BDJtabLinkSelected">Online 
                      Job Posting</span>&nbsp;&nbsp; <img src="images/pix_orange.gif" width="6" height="6" hspace="5"  style="vertical-align:middle"><span class="BDJtabLinkSelected">CV 
                      Bank Access</span></div>
                    <br> <span class="BDJFormTitle">Company Log In</span><br> 
                    <img src="images/pix_gray.gif" width="100%" height="1" vspace="5"><br> 
                    
                    <img src="images/pix_gray.gif" width="100%" height="1" vspace="5"><br> 
                    <br> <div align="center"> 
                      <span> <a href=<?php echo$this->escape($this->create)?>>Create New Account</a></span>
                      <br>
                      <span class="BDJTopMenuDivider">If you have not already 
                      created an account</span></div>
                    <br> <br> </td>

                  <td class="bodyRight"><img src="images/pix.gif" width="1" height="1" /></td>
                </tr>
                <tr> 
                  <td class="footerLeft"></td>
                  <td class="footerMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
                  <td class="footerRight"></td>
                </tr>
              </table>
            </FORM>

         
         
        </tr>
      </table>
</td>
  </tr>
  <tr>
    <td height="50" align="center" valign="bottom" class="BDJCopyright"></td>
  </tr>
</table>-->
<!--</div>
</div>-->
<h1>Company Login</h1>
<div>Welcome to the section for Employers at portaljobs Log into your Account to get the following online recruitment services:<br> &nbsp;</div>
<div><?php echo $this->login; ?></div><br><br><br><br><br><br>
Doesnot have employer account?<a href="">Click Here</a> to create new.
    </body>
</html>
