<div id="view-content">

        <table>
            <tr>
                <td><h1>List of Employers</h1></td>
            </tr>

        <?php
            $basepath = Zend_Controller_Front::getInstance()->getBaseUrl();
            foreach($this->paginator as $employer)
            {
                echo "<tr>";
                echo "<td>";
                echo "<a href='$basepath/jobs/jobsbyemployer/employerid/".$employer['EmployerID']
                ."'>" . $employer['EmployerName']." </a>";
                echo "</td>";
                echo "</tr>";
            }
        ?>
        </table>
    <?php
    if($this->paginator->getTotalItemCount() > $this->paginator->getItemCountPerPage())
        echo $this->paginationControl($this->paginator, 'Elastic', 'controls.phtml'); ?>
</div>