<div id="view-content">
        <table>
            <tr>
                <td>Search Jobs by Category</td>
            </tr>

        <?php
        
            $basepath = Zend_Controller_Front::getInstance()->getBaseUrl();
            foreach($this->paginator as $job)
            {
                echo "<tr>";
                echo "<td>";
                echo "<a href='$basepath/jobs/jobsbycategory?jobcatid=".$job['jobcategoryid']
                ."'>" . $job['jobcategory']. "(" . $job['jobcount']. ") </a>";
                echo "</td>";
                echo "</tr>";
            }
        ?>
        </table>
    <?php 
    if($this->paginator->getTotalItemCount() > $this->paginator->getItemCountPerPage())
        echo $this->paginationControl($this->paginator, 'Elastic', 'controls.phtml'); ?>
</div>
