^
<div id="welcome">
    <a href="
    <?php
    echo $this->url(array("controller"=>"index", "action"=>"add"));
    ?>">Add New Job Category</a>
    <table>

        <?php

            
            foreach($this ->jobCategories as $category)
            {
                echo "<tr>";
                echo "<td>" . $this->escape( $category->JobCategory) . "</td>";
                echo "</tr>";
            }
        ?>
    </table>
</div>