
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>

<title>Employer Home </title>


	</head>
	<body id="sys_background">
		<div id="outer">
			<div id="sys_banner" >


				<h1><a id="sys_heading" href="./">Employer Home</a></h1>
			</div>
			<div id="menu">
				<ul class='sys_navigation'>


                                               <li class="first"><a href=<?php echo$this->escape($this->home)?> title="Home">Home</a></li>
                                                    	<li><a href=<?php echo$this->escape($this->postjob)?> title="Post Job">Post Job</a></li>

                                                        <li><a href=<?php echo$this->escape($this->searchcv)?> title="Search Cv">Search CV</a></li>


													<li><a href=<?php echo$this->escape($this->servicecharge)?> title="Service Charge">Service charge</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Menu">Service Benifits</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Contacts">Contacts</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Other">Other</a></li>





													






													








									</ul>
			</div>
			<div id="content">
				    <div style="width: 100%; padding: 0px; margin: 0px" class="layout_1-column">

        <div id="layout_row1">
        
    
       <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
	<tr>
    <td style="padding-left:20px; padding-right:20px;">
	<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-top:1px solid #FFFFFF;">

      <tr>
        <td width="215" height="30" align="center"><img src="images/txt_corporate_panel.gif" width="161" height="14"></td>
        <td width="854" style="background-image:url(images/gradient_top.jpg); background-repeat:repeat-y;">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
        	<tr>
            <td class="BDJCompanyName" >&nbsp;&nbsp;Company Name: INSA</td>
              <td align="right"><img src="images/icons_logout2.gif" width="16" height="15" hspace="5" align="middle"><a href="logout.asp" class="BDJGreenArial11px"><strong>Logout</strong></a></td>
            </tr>

        </table>
		</td>
        </tr>
    </table>
    <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0">
      	<tr>
        <td width="215" valign="top" style="padding-top:30px;">
		
	
    <table width="190" border="0" cellspacing="0" cellpadding="0" id="tblSet2">
        <tr>

        <td class="headLeft"></td>
        <td class="headMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
        <td class="headRight"></td>
        </tr>
        
        <tr>
        <td class="bodyLeft"><img src="images/pix.gif" width="1" height="1" /></td>
        <td valign="top" class="body" style="padding:5px;"><span class="BDJFormTitle">Main Menu</span><br>
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>

        
      <div class="BDJWelcomeTxt">
         <img src="images/icons_addnew.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->postform)?> class='BDJNavLink'>Post a New Job</a><br>
        <img src="images/icons_account.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->findemployer)?> class='BDJNavLink'>Edit Account Info</a><br>
        <img src="images/icons_invoice.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->create)?> class='BDJNavLink'>Payment Status</a><br>  
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->create)?> class='BDJNavLink'>Contact Support</a><br>

        <img src="images/btn_icon_login.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->create)?> class='BDJNavLink'>Change Password</a><br>
        
        <!--
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>                      
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>
        -->
        

        </div>
       
        
        <img src="images/icons_logout.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href='logout.asp' class='BDJNavLink'>Logout</a><br>
        
        
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>
        <span class="BDJFormTitle">Account Status</span><br>
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
            
            <td class="BDJGrayArial12px">Online Job Posting<br>

            <img src="images/pix.gif" width="50" height="10"><br>
            CV Database Access</td>
            
    
            <td width="30" align="right" class="BDJNoticeVerdana11Red"><strong>						
            No&nbsp;<br>
            <img src="images/pix.gif" width="30" height="10"><br>
            No&nbsp;</strong></td>
            </tr>
        </table>

        
        
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"/><br/><span class="BDJFormTitle">Corporate Support</span><br/>
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"/>
       
       
        <br/>
        <span class="BDJtabLinkSelected">Help Desk:</span> <br/><span class="BDJGrayArial12px"><strong>9117179, 9140345, 01811410858, 01811410860</strong></span>
        <div  style="margin-top:5px;" align="justify" class="BDJRedArial11px">Please call us if you face any difficulty in accessing the online services or plan for subscribing to additional services</div>
        <div class="BDJWelcomeTxt"></div>

        </td>    
        <td class="bodyRight"><img src="images/pix.gif" width="1" height="1" /></td>
        </tr>
        
        <tr>
        <td class="footerLeft"></td>
        <td class="footerMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
        <td class="footerRight"></td>
        </tr>    
    </table>
	<script type="text/JavaScript">qm_create(0,true)</script>

		</td>
        
        <td width="745" valign="top"> 
       
        <form name="frmCorporateNewAccount" id="frmCorporateNewAccount" method="post" action=<?php echo$this->escape($this->action)?> onsubmit="return IsPageValid();"> <!--onsubmit="return IsPageValid();"-->
        <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #FFFFFF;">
        	<tr>
            <td height="30" class="BDJGrayArial12px">&nbsp;</td>
            <td align="right" class="BDJGrayArial12px">Fields marked by <img src="images/star.gif" width="7" height="7" hspace="1"> are mandatory</td>

            </tr>		
         </table>

		
        
        
        <!--
         COMPANY DETAILS:
         -->
         
         <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
            <tr>
            <td class="headLeft">&nbsp;</td>
            <td height="33" colspan="2" class="head"> 
            <?php $vlaues =$this->username;?>       
             Company Details</td>
            <td class="headRight">&nbsp;</td>
            </tr>

                        <!--COMPANY NAME:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td width="30%">Company Name <?php echo$this->escape($vlaues->getCompanyname())?> </td>
            <td width="70%" style="color:#333333">
           
            <input type="hidden" name="txtCompanyName" id="txtCompanyName" maxlength="120" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getCompanyname())?>  />
            <input type="hidden" name="txtPageType" id="txtPageType" value="Update"/>
            </td>

            <td class="bodyRight">&nbsp;</td>
            </tr>
        
            <!--ALTERNATIVE COMPANY NAME:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td>Alternative Company Name</td>
            <td>
            <input type="text" name="txtAliasName" id="txtAliasName" maxlength="50" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getAlternativeCompany())?> />

            <span class="BDJGrayArial12px" style="font-size:9px">N.B</span>
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
                
            <!--CONTACT PERSON:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td>Contact Person<img src="images/star.gif" width="7" height="7" hspace="5"></td>

            <td>
            <input type="text" name="txtContactPerson" id="txtContactPerson" maxlength="100" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getContactperson())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>

            <!--CONTACT PERSON's DESIGNATION:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>

            <td>Contact Person's Designation<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtDesignation" id="txtDesignation" maxlength="100" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getContactPersonDesignation())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
    
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>

            <td align="right" valign="top" style="padding-right:5px;"><span class="BDJGrayArial12px" style="font-size:9px">N.B.</span></td>
            <td style="padding-bottom:2px;">
            <span class="BDJGrayArial12px" style="font-size:11px">
            </span>

            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>

            <tr>
            <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
            <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
            <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
            </tr>		
         </table>

            
         <!--
         BUSINESS TYPE:
         -->
         <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
            <tr>
            <td class="headLeft">&nbsp;</td>
            <td height="33" colspan="2" class="head">Business Type</td>
            <td class="headRight">&nbsp;</td>
            </tr>
            
            <!--BUSINESS TYPES:-->
            <tr class="body">

            <td class="bodyLeft">&nbsp;</td>
            <td width="30%">Business Type<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td width="70%">	
            <?php $datas = $this->businessType;?> 				
            <select name="cboBusinessType"  id="cboBusinessType"  style="width:80%;">
                <option value="-1">Select</option>
                
              <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getBusinessType()?><?php if($datas[$i]->getBusinessType() == $this->escape($vlaues->getBusinessType())) echo ' selected'; ?> > 
                <?php echo$datas[$i]->getBusinessType()?></option>
			
               <?php } ?>
                     
                     <option value="-10" >Others</option>
                
            </select>
            </td>
            <td class="bodyRight">&nbsp;</td>

            </tr>
            
            <!--BUSINESS DESCRIPTION:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td valign="top" style="padding-top:3px; padding-bottom:2px;">Business Description</td>
            <td style="padding-bottom:2px;">
            <textarea name="txtDescription" id="txtDescription" class="BDJtextBox" style="width:80%; height:80px;"></textarea>
            </td>

            <td class="bodyRight">&nbsp;</td>
            </tr>
        
            <tr>
            <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
            <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
            <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
            </tr>		
         </table>
         
         <!--
         PRIMARY CONTACT DETAILS:
         -->

         <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
            <tr>
            <td class="headLeft">&nbsp;</td>
            <td height="33" colspan="2" class="head">Primary Contact Details</td>
            <td class="headRight">&nbsp;</td>
            </tr>
        
            <!--COMPANY ADDRESS:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>

            <td width="30%">Company Address<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td width="70%">
            <input type="text" name="txtCompanyAddress" id="txtCompanyAddress" maxlength="300" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getCompanyAddress())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
                            
            <!--COUNTRY:-->
            <tr class="body">

            <td class="bodyLeft">&nbsp;</td>
            <td>Country<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td>
             <?php $datas = $this->country;?> 
            <select name="cboCountry" id="cboCountry"  style="width:150px;"  onchange="PopulateCity(this.value);GetLocationList(this.value);">
                <option value="-1" selected="selected">Select</option>
                								      
                           <?for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getCountryName()?> <?php if($datas[$i]->getCountryName() == $this->escape($vlaues->getCountry())) echo ' selected'; ?>>  
               <?php echo$datas[$i]->getCountryName()?></option>
			
               <?php } ?>
                     								      
                                                		
            </select>		
            </td>

            <td class="bodyRight">&nbsp;</td>
            </tr>

            <!--CITY:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>City<img src="images/star.gif" width="7" height="7" hspace="5"></td>        
        <td id="tdCity">        
         <?php $datas = $this->city;?> 
             <select name="cboCity"  id="cboCity" style="width:150px;">
             	<option value="-1" selected="selected">Select</option>
                   <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getCityId()?>  <?php if($datas[$i]->getCityId() == $this->escape($vlaues->getCityId())) echo ' selected'; ?>> 
                <?php echo$datas[$i]->getCityName()?></option>
			
               <?php } ?>
			     					  
             </select>
        
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--CITY:-->
            <!--Area:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td id="tdAreaCaption">Area</td>        
            <td id="tdAreaControl">

              
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
        
            <!--BILLING ADDRESS:-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>

            <td>Billing Address<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtBillingAddress" id="txtBillingAddress" maxlength="150" size="50" class="BDJtextBox" style="width:80%;" value=<?php echo$this->escape($vlaues->getBillingAddress())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
    
            <!--CONTACT PHONE:-->
            <tr class="body">

            <td class="bodyLeft">&nbsp;</td>
            <td>Contact Phone<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtContactPhone" id="txtContactPhone" maxlength="30" size="50" class="BDJtextBox" style="width:50%;" value=
<?php echo$this->escape($vlaues->getContactPhone())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>

            <!--CONTACT EMAIL:-->

            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td>Contact E-Mail<img src="images/star.gif" width="7" height="7" hspace="5"></td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtEmail" id="txtEmail" maxlength="40" size="50" class="BDJtextBox" style="width:50%;" value=<?php echo$this->escape($vlaues->getContactMail())?> />
           
            <span class="BDJRedArial11px">[Do not type more then 1 e-mail address.]</span>
            </td>

            <td class="bodyRight">&nbsp;</td>
            </tr>

            <!--WEBSITE ADDRESS (URL):-->
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td>Website Address (URL)</td>
            <td style="padding-bottom:2px;">
            <input type="text" name="txtURL" id="txtURL" maxlength="50" size="50" class="BDJtextBox" style="width:50%;" value="<?php echo$this->escape($vlaues->getWebsiteAddress())?>" />

            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>
            
            <tr>
            <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
            <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
            <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
            </tr>		
         </table>

        <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" style="margin-top:2px;">
            <tr class="body">
            <td class="bodyLeft">&nbsp;</td>
            <td colspan="2" align="center" style="height:50px;">
            <input type="submit" name="edit" value="Edit Employer" width="109" height="21" />
            <input type="hidden" name="txtuserID" id="txtuserID" value=<?php echo$this->escape($vlaues->getUserId())?> />
            </td>
            <td class="bodyRight">&nbsp;</td>
            </tr>

        </table>			
    	</form>
        <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
            <td style="padding-left:20px; padding-right:20px;"></td>
            </tr>
            <tr>
            <td height="6" align="center" valign="top" class="BDJCopyright"></td>
            </tr>	
        </table>	
        

        </td>
        </tr>
        </table>
        
     
            
            
            
        </div>
        
        
    </div>
			</div>
            <div id="footer-wrap">
			<div id='sys_footer' class='sys_footer'>Designed by <a href='http://www.freecsstemplates.org' target='_blank'>xxxxxxxxxxxxxxxxx</a></div>




            </div>
        </div>
    </body>