<!--<head>

<title>Employer Home </title>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>

</head>

 <table width="60%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:15px; padding-right:15px; padding-top:34px;">
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
        
        
       
        <tr>
          <td rowspan="5" align="center" valign="top"> 
            ### Form table start ###
           <h1>Company Login</h1>
<div>Welcome to the section for Employers at portaljobs Log into your Account to get the following online recruitment services:<br> &nbsp;</div>
<div><?php echo $this->login; ?></div><br><br><br><br><br><br>
Doesnot have employer account?
<a href=<?php echo$this->escape($this->create)?>>Click Here</a> to create new.
    

         
         
        </tr>
      </table>
</td>
  </tr>
  <tr>
    <td height="50" align="center" valign="bottom" class="BDJCopyright"></td>
  </tr>
</table>-->
<!--</div>
</div>-->

</html>
