<head>

<title>Employer Home </title>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>
</head>
<body id="sys_background">
		<div id="outer">
			<div id="sys_banner" >


				<h1><a id="sys_heading" href="./">Employer Home</a></h1>
			</div>
			<div id="menu">
				<ul class='sys_navigation'>



													<li class="first"><a href=<?=$this->escape($this->home)?> title="Home">Home</a></li>
                                                    	<li><a href=<?=$this->escape($this->postjob)?> title="Post Job">Post Job</a></li>

                                                        <li><a href=<?=$this->escape($this->searchcv)?> title="Search Cv">Search CV</a></li>


													<li><a href=<?=$this->escape($this->servicecharge)?> title="Service Charge">Service charge</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Menu">Service Benifits</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Contacts">Contacts</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Other">Other</a></li>





													








									</ul>
			</div>
			
        <div id="layout_row1">
			<div id="layout_row1">
        <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:15px; padding-right:15px; padding-top:34px;">
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
        
        
       
        <tr>
          <td rowspan="5" align="center" valign="top"> 
            <!--### Form table start ###-->
            <FORM name="frmDefault" id="frmDefault" method="post" action= <?=$this->escape($this->login)?> > <!--https://bdjobs.sslcert11.com/corporate/corporate_submit.asp-->

              <table width="90%" border="0" cellspacing="0" cellpadding="0" id="tblSet2">
                <tr> 
                  <td class="headLeft"></td>
                  <td class="headMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
                  <td class="headRight"></td>
                </tr>
                <tr> 
                  <td class="bodyLeft"><img src="images/pix.gif" width="1" height="1" /></td>
                  <td class="body" style="padding:5px;"><div class="BDJWelcomeTxt">Welcome 
                      to the section for Employers at portaljobs Log into your 
                      Account to get the following online recruitment services:<br>

                      &nbsp;</div>
                    <div align="center"><img src="images/pix_orange.gif" width="6" height="6" hspace="5" style="vertical-align:middle"><span class="BDJtabLinkSelected">Online 
                      Job Posting</span>&nbsp;&nbsp; <img src="images/pix_orange.gif" width="6" height="6" hspace="5"  style="vertical-align:middle"><span class="BDJtabLinkSelected">CV 
                      Bank Access</span></div>
                    <br> <span class="BDJFormTitle">Company Log In</span><br> 
                    <img src="images/pix_gray.gif" width="100%" height="1" vspace="5"><br> 
                    <table width="100%" border="0" cellspacing="0" cellpadding="0" style="padding-top:5px;">
                      
                      <tr> 
                        <td height="35" align="right" class="BDJtabLinkNormal">User 
                          Name</td>

                        <td align="right"><INPUT type="text" name="NAME" id="NAME" size="20" maxlength="40" class="BDJtextBox" style="width:130px;"></td>
                      </tr>
                      <tr> 
                        <td height="35" align="right" class="BDJtabLinkNormal">Password</td>
                        <td align="right"><INPUT type="password" name="PASS" id="PASS" size="20" class="BDJtextBox" style="width:130px;"></td>
                      </tr>
                                          <tr> 
                        <td height="22" colspan="2" align="right"><div align="right" style="margin-top:5px;"> 
                            <INPUT type="submit" name="Login" value="Login" width="79" height="23">

                          </div></td>
                      </tr>
                      <tr> 
                        <td height="22" colspan="2" align="right"><a href="http://www.bdjobs.com/corporate/password" class="BDJForgotVerdana12">Forgot 
                          your company password?</a></td>
                      </tr>
                    </table>
                    <img src="images/pix_gray.gif" width="100%" height="1" vspace="5"><br> 
                    <br> <div align="center"> 
                      <span> <a href= <?=$this->escape($this->create)?>>Create New Account</a></span>
                      <br>
                      <span class="BDJTopMenuDivider">If you have not already 
                      created an account</span></div>
                    <br> <br> <div class="BDJWelcomeTxt">(<span class="BDJNoticeVerdana11Red">Attention 
                      New Users !</span> To<strong> post jobs</strong> or access 
                      online CV Bank, please create your <strong>corporate account</strong> 
                      first.)</div></td>

                  <td class="bodyRight"><img src="images/pix.gif" width="1" height="1" /></td>
                </tr>
                <tr> 
                  <td class="footerLeft"></td>
                  <td class="footerMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
                  <td class="footerRight"></td>
                </tr>
              </table>
            </FORM>

            <table width="90%" border="0" cellspacing="0" cellpadding="0" id="tblSet2">
              <tr> 
                <td width="6" class="headLeft"></td>
                <td colspan="2" class="headMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
                <td width="6" class="headRight"></td>
              </tr>
              <tr> 
                <td class="bodyLeft"><img src="images/pix.gif" width="1" height="1" /></td>
                <td width="153" class="body"  style="padding:5px;" valign="top">  <span class="BDJtabLinkSelected">ForTechnical 
                  Support </span><br> 
                  <br>

                  Email:<a href="mailto:support@portaljobs.com">support@portaljobs
                    </a><br>
                  Tel:  8124366, 9144559
                  <br>
                  Mobile: 07345886884885, 07345886884885 
                    <br>
                    <br>
                <span class="BDJtabLinkSelected">For Accounts </span>
                <br>

                 01811410857, 8124366 </td>
                <td width="168" class="body" valign="top"  style="padding:5px;"><span class="BDJtabLinkSelected">For 
                  Sales Support</span><br> <br>
                  Email:<a href="mailto:sales@portaljobs.com">sales@portaljobs</a><br>
                  Mobile:07345886884885, 01919 (235627) , 01841, <br>
                  <br>

                   01811410851 <br>
                  Tel: 9117179, 9140345</td>
                <td class="bodyRight"><img src="images/pix.gif" width="1" height="1" /></td>
              </tr>
              <tr> 
                <td class="footerLeft"></td>
                <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
                <td class="footerRight"></td>

              </tr>
            </table></td>
          <td colspan="2" align="left" valign="top" style="padding-left:20px; padding-bottom:10px;">
		  
               
				</td>
        </tr>
        <tr>
          <td colspan="2" align="center" valign="top"><div align="left" style="width:90%" class="BDJFormTitle">portaljobs
              SERVICES FOR EMPLOYERS:</div></td>
        </tr>

        <tr>
          <td align="center" valign="top">
          <table width="90%" border="0" cellspacing="0" cellpadding="0" id="tblSet1" >
              <tr> 
                <td class="headLeft">&nbsp;</td>
                <td class="head">&nbsp;&nbsp;Online Job Posting/Announcement</td>
                <td class="headRight">&nbsp;</td>
              </tr>
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>

                <td style="height:210px;" valign="top"><UL>
                    <LI><strong>Instant Job Posting from your office</strong></LI>
                    <LI><strong>Job Announcements</strong> displayed at the category/ 
                      classified section. Job will be live for max. <strong>30 
                      days</strong></LI>
                    <LI>Online Application Facility for candidates</LI>
                    <LI>Online Control Panel for <strong>Searching right candidate</strong> 
                      from the applicant pool</LI>

                  </UL></td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td align="center"><a href="javascript:showLayer('v1' , 375 , 200 , 0 , 400 );" ><strong class="BDJNoticeVerdana11Red">Click 
                  here for Pricing</strong></a></td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
              <tr> 
                <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>

                <td class="footerMiddle"><img src="images/pix.gif" width="1" height="1"></td>
                <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
              </tr>
            </table></td>
          <td align="center" valign="top"><table width="90%" border="0" cellspacing="0" cellpadding="0" id="tblSet1">
              <tr> 
                <td height="35" class="headLeft">&nbsp;</td>
                <td class="head">&nbsp;&nbsp;Online CV Database Access</td>
                <td class="headRight">&nbsp;</td>

              </tr>
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td  style="height:210px;"  valign="top"><UL>
                    <LI>Access to online CV database <strong>
                      professionals</strong></LI>
                    <LI>Advanced Searching tools for locating right candidate 
                      easily</LI>
                    <LI>Search conditions include <strong>education, experience, 
                      specialization and other personal info</strong> (e.g. age, 
                      gender, location etc.)</LI>

                  </UL></td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td align="center"><a href="javascript:showLayer('v2' , 375 , 150 , 0 , 400 );"><strong class="BDJNoticeVerdana11Red">Click 
                  here for Pricing</strong></a></td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
              <tr> 
                <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>

                <td class="footerMiddle"><img src="images/pix.gif" width="1" height="1"></td>
                <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
              </tr>
            </table></td>
        </tr>
        <tr> 
          <td height="30" align="center" valign="bottom" style="padding-bottom:4px;"><div align="left" style="width:90%" class="BDJFormTitle"></div></td>
          <td align="right" valign="bottom" class="BDJNoticeVerdana11Red" style="padding-bottom:4px;padding-right:15px;"><strong>&nbsp;</strong></td>
        </tr>

        <tr> 
          <td align="center" valign="top"><table width="90%" border="0" cellspacing="0" cellpadding="0" id="tblSet1">
              <tr> 
                <td class="headLeft">&nbsp;</td>
                <td class="head">&nbsp;&nbsp;Hot Job Announcement </td>
                <td class="headRight">&nbsp;</td>
              </tr>
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td  style="height:210px;" valign="top"><UL>

                    <LI><strong>Job Announcements</strong> (with company logo) 
                      displayed at the <strong>homepage</strong> for max. 10 days 
                      (with 30 days display facility at category section)</LI>
                    <LI><strong>Customized</strong> job detail page (linked with 
                      home page) designed by Bdjobs.com</LI>
                    <LI><strong>Special Job notification</strong> to prospective 
                      qualified candidates through e-mail</LI>

                  </UL></td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td align="center"><a href="javascript:showLayer('v3' , 400 , 150 , 0 , 400 );"><strong class="BDJNoticeVerdana11Red">Click 
                  here for Pricing</strong></a></td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
              <tr> 
                <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>

                <td class="footerMiddle"><img src="images/pix.gif" width="1" height="1"></td>
                <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
              </tr>
            </table></td>
          
        </tr>
        <tr> 
          <td width="40%" rowspan="2" valign="top"> <div   style="width:350px;"  class="BDJWelcomeTxt"> 
              <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr> 
                  <td width="5%">&nbsp;</td>

                  <td width="90%">&nbsp;</td>
                  <td width="5%">&nbsp;</td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td><div align="center">
                      <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                        <tr>
                          <td><div align="center"><!--a href="http://www.GBangladesh.com" target="_blank"></a-->

                          </div></td>
                        </tr>
                      </table>
                    </div></td>
                  <td>&nbsp;</td>
                </tr>
                <tr> 
                  <td width="5%">&nbsp;</td>
                  <td width="90%">&nbsp;</td>

                  <td width="5%">&nbsp;</td>
                </tr>
                <tr> 
                  <td width="5%">&nbsp;</td>
                  <td width="90%"> <span class="BDJtabLinkSelected">portaljobs
                    Limited </span><br>
                    <font color="#666666" size="1" face="Verdana"><strong>2th Floor <br>ABB Building Stockholm Sweden</strong></font> <br> </td>

                  <td width="5%">&nbsp;</td>
                </tr>
              </table>
            </div></td>
          <td height="30" align="center" valign="bottom" style="padding-bottom:4px;"><div align="left" style="width:90%" class="BDJFormTitle"></div></td>
          <td valign="bottom" style="padding-bottom:4px;">&nbsp;</td>
        </tr>
        
      </table>
</td>
  </tr>
  <tr>
    <td height="50" align="center" valign="bottom" class="BDJCopyright"></td>
  </tr>
</table>
</div>
</div>
    </body>
</html>
