
<title>Employer Home </title>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>

	</head>
	<body id="sys_background">
		<div id="outer">
		
			<div id="menu">
				<ul class='sys_navigation'>



													<li class="first"><a href=<?php echo$this->escape($this->home)?> title="Home">Home</a></li>
                                                    	<li><a href=<?php echo$this->escape($this->postjob)?> title="Post Job">Post Job</a></li>

                                                        <li><a href=<?php echo$this->escape($this->searchcv)?> title="Search Cv">Search CV</a></li>


													<li><a href=<?php echo$this->escape($this->servicecharge)?> title="Service Charge">Service charge</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Menu">Service Benifits</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Contacts">Contacts</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Other">Other</a></li>





													


													








									</ul>
			</div>
			
        
        <div id="layout_row1">
        
        <table width="80%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
	<form name="frmCorporateNewAccount" id="frmCorporateNewAccount" method="post" action=<?php echo$this->escape($this->action)?> >
	<tr>
    <td style="padding-left:20px; padding-right:20px;">
	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #FFFFFF;">
		<tr>
        <td height="30" class="BDJGrayArial12px">&nbsp;</td>
        
        <td align="right" class="BDJGrayArial12px">Fields marked by <img src="images/star.gif" width="7" height="7" hspace="1"> are mandatory</td>

        </tr>		
        
        <tr>
        <td colspan="2">
		 <?php echo $this->wrongPassword;?>        
        </td>
        </tr>
	</table>
        
            <!--
	ACCOUNT INFORMATION:
	-->    
	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4">				
    	<tr>
        <td class="headLeft">&nbsp;</td>

        <td height="33" colspan="2" class="head">
		Account Information
		<input type="hidden" name="txtPageType" id="txtPageType" value="Insert" />
		</td>
        <td class="headRight">&nbsp;</td>
        </tr>
                <!--USER NAME:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>

        <td width="30%">User Name<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td width="70%">
		<input type="text" name="txtUserName" id="txtUserName" maxlength="20" size="50" class="BDJtextBox" style="width:30%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--PASSWORD:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td>Password<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td>
		<input type="password" name="txtPassword" id="txtPassword" maxlength="8" size="50" class="BDJtextBox" style="width:30%;" value="" />
		<span class="BDJRedArial11px">[Maximum 8 Characters.]</span>
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

        
		<!--CONFIRM PASSWORD:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Confirm Password<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="password" name="txtConfirmPassword" id="txtConfirmPassword" maxlength="8" size="50" class="BDJtextBox" style="width:30%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>

        </tr>
<tr>
        <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
        <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
        <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
        </tr>		
	</table>
	<!--
	COMPANY DETAILS:
	-->
	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
    	<tr>

        <td class="headLeft">&nbsp;</td>
        <td height="33" colspan="2" class="head">Company Details</td>
        <td class="headRight">&nbsp;</td>
        </tr>
		
        <!--COMPANY NAME:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td width="30%">Company Name<img src="images/star.gif" width="7" height="7" hspace="5"></td>

        <td width="70%">
		<input type="text" name="txtCompanyName" id="txtCompanyName" maxlength="120" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--ALTERNATIVE COMPANY NAME:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Alternative Company Name</td>

        <td>
		<input type="text" name="txtAliasName" id="txtAliasName" maxlength="50" size="50" class="BDJtextBox" style="width:80%;" value="" />
		
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--CONTACT PERSON:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td>Contact Person<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td>
		<input type="text" name="txtContactPerson" id="txtContactPerson" maxlength="100" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--CONTACT PERSON's DESIGNATION:-->

		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Contact Person's Designation<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtDesignation" id="txtDesignation" maxlength="100" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td align="right" valign="top" style="padding-right:5px;"><span class="BDJGrayArial12px" style="font-size:9px">N.B.</span></td>
        
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<tr>
        <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
        <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
        <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
        </tr>		
	</table>

	<!--
	BUSINESS TYPE:
	-->
	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
    	<tr>
        <td class="headLeft">&nbsp;</td>
        <td height="33" colspan="2" class="head">Business Type</td>
        <td class="headRight">&nbsp;</td>
        </tr>
		
        <!--BUSINESS TYPES:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td width="30%">Business Type<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td width="70%">
		<?php $datas = $this->businessType;?> 
		
		
		<select name="cboBusinessType" id="cboBusinessType"  style="width:80%;" >
			<option value="-1">Select</option>
			
		     
              <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getBusinessType()?> >    <?php echo$datas[$i]->getBusinessType()?></option>
			
               <?php } ?>
				 <option value="-10">Others</option>
			
		</select>
		</td>
        <td class="bodyRight">&nbsp;</td>

        </tr>
        <!--BUSINESS DESCRIPTION:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td valign="top" style="padding-top:3px; padding-bottom:2px;">Business Description</td>
        <td style="padding-bottom:2px;">
		<textarea name="txtDescription" id="txtDescription" class="BDJtextBox" style="width:80%; height:80px;"></textarea>
		</td>

        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<tr>
        <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
        <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
        <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
        </tr>		
	</table>
	<!--
	PRIMARY CONTACT DETAILS:
	-->

	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
    	<tr>
        <td class="headLeft">&nbsp;</td>
        <td height="33" colspan="2" class="head">Primary Contact Details</td>
        <td class="headRight">&nbsp;</td>
        </tr>
		
        <!--COMPANY ADDRESS:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>

        <td width="30%">Company Address<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td width="70%">
		<input type="text" name="txtCompanyAddress" id="txtCompanyAddress" maxlength="300" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--COUNTRY:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td>Country<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td> 
        <?php $datas = $this->country;?>  
               
		<select name="cboCountry" id="cboCountry"  style="width:150px;" onchange="ChangePricingPolicy();PopulateCity(this.value);GetLocationList(this.value);"> <!---->
			<option value="-1" selected="selected">Select</option>
			 <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getCountryName()?> >    <?php echo$datas[$i]->getCountryName()?></option>
			
               <?php } ?>
					   			     		
		</select>	
		</td>

        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--CITY:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>City<img src="images/star.gif" width="7" height="7" hspace="5"></td>        
        <td id="tdCity">        
         <?php $datas = $this->city;?>  
             <select name="cboCity" id="cboCity" style="width:150px;">
             	<option value="-1" selected="selected">Select</option>
                  <?php for($i = 0; $i < count($datas);$i++){ ?>            
             <option value=<?php echo$datas[$i]->getCityId()?> >    <?php echo$datas[$i]->getCityName()?></option>
			
               <?php } ?>
			     
					
             </select>
        
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--BILLING ADDRESS:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>

        <td>Billing Address<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtBillingAddress" id="txtBillingAddress" maxlength="150" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--CONTACT PHONE:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td>Contact Phone<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtContactPhone" id="txtContactPhone" maxlength="30" size="50" class="BDJtextBox" style="width:50%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--CONTACT EMAIL:-->

		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Contact E-Mail<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtEmail" id="txtEmail" maxlength="40" size="50" class="BDJtextBox" style="width:50%;" value="" />
		<span class="BDJRedArial11px">[Do not type more than 1 e-mail address.]</span>
		</td>
        <td class="bodyRight">&nbsp;</td>

        </tr>

		<!--WEBSITE ADDRESS (URL):-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Website Address (URL)</td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtURL" id="txtURL" maxlength="50" size="50" class="BDJtextBox" style="width:50%;" value="">
		</td>

        <td class="bodyRight">&nbsp;</td>
        </tr>
		
		<tr>
        <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
        <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
        <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
        </tr>		
	</table>
	    		    
        <table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" style="margin-top:2px;">

		<tr class="body">
		<td class="bodyLeft">&nbsp;</td>
		<td colspan="2" align="center" style="height:50px;">
		<input type="submit" value ="Register" name ="register" width="109" height="21">
        <input type="hidden" name="txtCity1" id="txtCity1" value="" />
        <input type="hidden" name="txtArea1" id="txtArea1" value="" />
        </td>
		<td class="bodyRight">&nbsp;</td>
		</tr>

	</table>			
	</td>
	</tr>
	
</FORM>
	<tr>
    <td height="10" align="center" valign="top" class="BDJCopyright"></td>
	</tr>	
</table>

       

        
     
            
            
            
        </div>
    </div>
			</div>
            
        </div>
    </body>