
<title>Employer Home </title>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>

	</head>
	<body id="sys_background">
		<div id="outer">
			<div id="sys_banner" >


				<h1><a id="sys_heading" href="./">Employer Home</a></h1>
			</div>
			<div id="menu">
				<ul class='sys_navigation'>



													<li class="first"><a href=<?=$this->escape($this->home)?> title="Home">Home</a></li>
                                                    	<li><a href=<?=$this->escape($this->postjob)?> title="Post Job">Post Job</a></li>

                                                        <li><a href=<?=$this->escape($this->searchcv)?> title="Search Cv">Search CV</a></li>


													<li><a href=<?=$this->escape($this->servicecharge)?> title="Service Charge">Service charge</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Menu">Service Benifits</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Contacts">Contacts</a></li>





													<li><a href=<?=$this->escape($this->contact)?> title="Other">Other</a></li>





													


													








									</ul>
			</div>
			
        
        <div id="layout_row1">
        
        <table width="80%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
	<form name="frmCorporateNewAccount" id="frmCorporateNewAccount" method="post" action=<?=$this->escape($this->action)?> >
	<tr>
    <td style="padding-left:20px; padding-right:20px;">
	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #FFFFFF;">
		<tr>
        <td height="30" class="BDJGrayArial12px">&nbsp;</td>
        <td align="right" class="BDJGrayArial12px">Fields marked by <img src="images/star.gif" width="7" height="7" hspace="1"> are mandatory</td>

        </tr>		
        
        <tr>
        <td colspan="2">
		        
        </td>
        </tr>
	</table>
        
            <!--
	ACCOUNT INFORMATION:
	-->    
	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4">				
    	<tr>
        <td class="headLeft">&nbsp;</td>

        <td height="33" colspan="2" class="head">
		Account Information
		<input type="hidden" name="txtPageType" id="txtPageType" value="Insert" />
		</td>
        <td class="headRight">&nbsp;</td>
        </tr>
                <!--USER NAME:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>

        <td width="30%">User Name<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td width="70%">
		<input type="text" name="txtUserName" id="txtUserName" maxlength="20" size="50" class="BDJtextBox" style="width:30%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--PASSWORD:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td>Password<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td>
		<input type="password" name="txtPassword" id="txtPassword" maxlength="8" size="50" class="BDJtextBox" style="width:30%;" value="" />
		<span class="BDJRedArial11px">[Maximum 8 Characters.]</span>
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

        
		<!--CONFIRM PASSWORD:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Confirm Password<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="password" name="txtConfirmPassword" id="txtConfirmPassword" maxlength="8" size="50" class="BDJtextBox" style="width:30%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>

        </tr>
<tr>
        <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
        <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
        <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
        </tr>		
	</table>
	<!--
	COMPANY DETAILS:
	-->
	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
    	<tr>

        <td class="headLeft">&nbsp;</td>
        <td height="33" colspan="2" class="head">Company Details</td>
        <td class="headRight">&nbsp;</td>
        </tr>
		
        <!--COMPANY NAME:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td width="30%">Company Name<img src="images/star.gif" width="7" height="7" hspace="5"></td>

        <td width="70%">
		<input type="text" name="txtCompanyName" id="txtCompanyName" maxlength="120" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--ALTERNATIVE COMPANY NAME:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Alternative Company Name</td>

        <td>
		<input type="text" name="txtAliasName" id="txtAliasName" maxlength="50" size="50" class="BDJtextBox" style="width:80%;" value="" />
		
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--CONTACT PERSON:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td>Contact Person<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td>
		<input type="text" name="txtContactPerson" id="txtContactPerson" maxlength="100" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--CONTACT PERSON's DESIGNATION:-->

		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Contact Person's Designation<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtDesignation" id="txtDesignation" maxlength="100" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td align="right" valign="top" style="padding-right:5px;"><span class="BDJGrayArial12px" style="font-size:9px">N.B.</span></td>
        
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<tr>
        <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
        <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
        <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
        </tr>		
	</table>

	<!--
	BUSINESS TYPE:
	-->
	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
    	<tr>
        <td class="headLeft">&nbsp;</td>
        <td height="33" colspan="2" class="head">Business Type</td>
        <td class="headRight">&nbsp;</td>
        </tr>
		
        <!--BUSINESS TYPES:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td width="30%">Business Type<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td width="70%">
		<select name="cboBusinessType" id="cboBusinessType"  style="width:80%;" >
			<option value="-1">Select</option>
			
				       <option value="13" >Advertising Agency</option>
				 
				       <option value="48" >Agro based firms (incl. Agro Processing/Seed/GM)</option>

				 
				       <option value="43" >Airline/GSA</option>
				 
				       <option value="52" >Architecture/Interior Design Firm</option>
				 
				       <option value="38" >Audit Firms /Tax Consultant</option>
				 
				       <option value="70" >Automobile Companies</option>
				 
				       <option value="Banks" >Banks</option>
				 
				       <option value="18" >BPO</option>

				 
				       <option value="37" >Buying House (Garments)</option>
				 
				       <option value="68" >Call Center</option>
				 
				       <option value="67" >Chemical Industries</option>
				 
				       <option value="27" >Clearing and Forwarding (C and F) companies</option>
				 
				       <option value="20" >Computer Hardware/Network Companies</option>

				 
				       <option value="34" >Consulting Firms</option>
				 
				       <option value="59" >Cosmetics/Personal Care</option>
				 
				       <option value="14" >Design/Printing/Publishing</option>
				 
				       <option value="23" >Development Agencies</option>
				 
				       <option value="54" >Direct Selling/Marketing Service Company</option>
				 
				       <option value="8" >Distribution Companies/Wholesale</option>

				 
				       <option value="11" >Education (School and Colleges)</option>
				 
				       <option value="10" >Education (Universities)</option>
				 
				       <option value="61" >Electronic Equipment/Home Appliances</option>
				 
				       <option value="31" >Embassies/Foreign Consulate</option>
				 
				       <option value="32" >Engineering Firms</option>
				 
				       <option value="15" >Event Management</option>

				 
				       <option value="47" >Food (Packaged)/Beverage</option>
				 
				       <option value="64" >Freight forwarding</option>
				 
				       <option value="35" >Garments (Woven and Knitting)</option>
				 
				       <option value="21" >Governement Organizations</option>
				 
				       <option value="66" >Group of Companies</option>
				 
				       <option value="39" >Hospitals/Clinic/Diagonastic Centre</option>

				 
				       <option value="41" >Hotels/Rosorts</option>
				 
				       <option value="51" >Immigration and Education Consultancy Service</option>
				 
				       <option value="55" >Indenting Firm</option>
				 
				       <option value="2" >Insurance</option>
				 
				       <option value="4" >Investment/Merchant Banking</option>
				 
				       <option value="19" >ISP</option>

				 
				       <option value="17" >IT Enabled Service</option>
				 
				       <option value="57" >Law Firm</option>
				 
				       <option value="3" >Leasing</option>
				 
				       <option value="26" >Logistic/Courier/Air Express Companies</option>
				 
				       <option value="53" >Manpower Recruitment</option>
				 
				       <option value="6" >Manufacturing (FMCG)</option>

				 
				       <option value="7" >Manufacturing (Light Engineering and Heavy Industry)</option>
				 
				       <option value="33" >Market Research Firms</option>
				 
				       <option value="30" >Media/Public Relation Companies</option>
				 
				       <option value="62" >Medical Equipment</option>
				 
				       <option value="28" >Multinational Companies</option>
				 
				       <option value="29" >Newspaper/Magazine</option>

				 
				       <option value="22" >NGOs</option>
				 
				       <option value="65" >Overseas Companies</option>
				 
				       <option value="40" >Pharmaceutical/Medicine Companies</option>
				 
				       <option value="60" >Poultry/Dairy/Veterinary</option>
				 
				       <option value="49" >Power Equipment/Generator/CNG</option>
				 
				       <option value="63" >Real Estate/ Developer</option>

				 
				       <option value="42" >Resturants</option>
				 
				       <option value="9" >Retail/Shops</option>
				 
				       <option value="56" >Security Service Company</option>
				 
				       <option value="71" >Share Brokerage/ Securities House</option>
				 
				       <option value="25" >Shipping</option>
				 
				       <option value="46" >Shrimp/Hachery</option>

				 
				       <option value="16" >Software Companies</option>
				 
				       <option value="45" >Tannery/Footwear</option>
				 
				       <option value="50" >Tea Company</option>
				 
				       <option value="5" >Telecommunication</option>
				 
				       <option value="36" >Textile (Spinning, Weaving, Knitting, Dyeing/Finishing)</option>
				 
				       <option value="69" >Tobacco</option>

				 
				       <option value="24" >Trading or Export/Import</option>
				 
				       <option value="12" >Training Institutues</option>
				 
				       <option value="44" >Travel Agents/Tour Operators</option>
				 
			   	 <option value="-10">Others</option>
			
		</select>
		</td>
        <td class="bodyRight">&nbsp;</td>

        </tr>
        <!--BUSINESS DESCRIPTION:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td valign="top" style="padding-top:3px; padding-bottom:2px;">Business Description</td>
        <td style="padding-bottom:2px;">
		<textarea name="txtDescription" id="txtDescription" class="BDJtextBox" style="width:80%; height:80px;"></textarea>
		</td>

        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<tr>
        <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
        <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
        <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
        </tr>		
	</table>
	<!--
	PRIMARY CONTACT DETAILS:
	-->

	<table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" id="tblSet4" style="margin-top:15px;">				
    	<tr>
        <td class="headLeft">&nbsp;</td>
        <td height="33" colspan="2" class="head">Primary Contact Details</td>
        <td class="headRight">&nbsp;</td>
        </tr>
		
        <!--COMPANY ADDRESS:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>

        <td width="30%">Company Address<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td width="70%">
		<input type="text" name="txtCompanyAddress" id="txtCompanyAddress" maxlength="300" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--COUNTRY:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td>Country<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td>        
		<select name="cboCountry" id="cboCountry"  style="width:150px;" onchange="ChangePricingPolicy();PopulateCity(this.value);GetLocationList(this.value);"> <!---->
			<option value="-1" selected="selected">Select</option>
			
					   <option value="Afghanistan" >Afghanistan</option>
			     
					   <option value="Albania" >Albania</option>

			     
					   <option value="Algeria" >Algeria</option>
			     
					   <option value="American Samoa" >American Samoa</option>
			     
					   <option value="Andorra" >Andorra</option>
			     
					   <option value="Angola" >Angola</option>
			     
					   <option value="Anguilla" >Anguilla</option>
			     
					   <option value="Antarctica" >Antarctica</option>

			     
					   <option value="Antigua" >Antigua</option>
			     
					   <option value="Argentina" >Argentina</option>
			     
					   <option value="Armenia" >Armenia</option>
			     
					   <option value="Aruba" >Aruba</option>
			     
					   <option value="Australia" >Australia</option>
			     
					   <option value="Austria" >Austria</option>

			     
					   <option value="Azerbaijan" >Azerbaijan</option>
			     
					   <option value="Bahamas" >Bahamas</option>
			     
					   <option value="Bahrain" >Bahrain</option>
			     
					   <option value="Bangladesh"  selected="selected" >Bangladesh</option>
			     
					   <option value="Barbados" >Barbados</option>
			     
					   <option value="Belarus" >Belarus</option>

			     
					   <option value="Belgium" >Belgium</option>
			     
					   <option value="Belize" >Belize</option>
			     
					   <option value="Benin" >Benin</option>
			     
					   <option value="Bermuda" >Bermuda</option>
			     
					   <option value="Bhutan" >Bhutan</option>
			     
					   <option value="Bolivia" >Bolivia</option>

			     
					   <option value="Bosnia and Herzegovina" >Bosnia and Herzegovina</option>
			     
					   <option value="Botswana" >Botswana</option>
			     
					   <option value="Brazil" >Brazil</option>
			     
					   <option value="British Virgin Islands" >British Virgin Islands</option>
			     
					   <option value="Brunei" >Brunei</option>
			     
					   <option value="Bulgaria" >Bulgaria</option>

			     
					   <option value="Burkina Faso" >Burkina Faso</option>
			     
					   <option value="Burma" >Burma</option>
			     
					   <option value="Burundi" >Burundi</option>
			     
					   <option value="Cambodia" >Cambodia</option>
			     
					   <option value="Cameroon" >Cameroon</option>
			     
					   <option value="Canada" >Canada</option>

			     
					   <option value="Cape Verde" >Cape Verde</option>
			     
					   <option value="Central African Republic" >Central African Republic</option>
			     
					   <option value="Chad" >Chad</option>
			     
					   <option value="Chile" >Chile</option>
			     
					   <option value="China" >China</option>
			     
					   <option value="Colombia" >Colombia</option>

			     
					   <option value="Comoros" >Comoros</option>
			     
					   <option value="Congo" >Congo</option>
			     
					   <option value="Congo (Zaire)" >Congo (Zaire)</option>
			     
					   <option value="Cook Islands" >Cook Islands</option>
			     
					   <option value="Costa Rica" >Costa Rica</option>
			     
					   <option value="Cote d'Ivoire (Ivory Coast)" >Cote d'Ivoire (Ivory Coast)</option>

			     
					   <option value="Croatia" >Croatia</option>
			     
					   <option value="Cuba" >Cuba</option>
			     
					   <option value="Cyprus" >Cyprus</option>
			     
					   <option value="Czech Republic" >Czech Republic</option>
			     
					   <option value="Denmark" >Denmark</option>
			     
					   <option value="Djibouti" >Djibouti</option>

			     
					   <option value="Dominica" >Dominica</option>
			     
					   <option value="Dominican Republic" >Dominican Republic</option>
			     
					   <option value="East Timor" >East Timor</option>
			     
					   <option value="Ecuador" >Ecuador</option>
			     
					   <option value="Egypt" >Egypt</option>
			     
					   <option value="El Salvador" >El Salvador</option>

			     
					   <option value="Equatorial Guinea" >Equatorial Guinea</option>
			     
					   <option value="Eritrea" >Eritrea</option>
			     
					   <option value="Estonia" >Estonia</option>
			     
					   <option value="Ethiopia" >Ethiopia</option>
			     
					   <option value="Falkland Islands" >Falkland Islands</option>
			     
					   <option value="Federated States of Micronesia" >Federated States of Micronesia</option>

			     
					   <option value="Fiji" >Fiji</option>
			     
					   <option value="Finland" >Finland</option>
			     
					   <option value="France" >France</option>
			     
					   <option value="French Guiana" >French Guiana</option>
			     
					   <option value="French Polynesia" >French Polynesia</option>
			     
					   <option value="Gabon" >Gabon</option>

			     
					   <option value="Gaza Strip and West Bank" >Gaza Strip and West Bank</option>
			     
					   <option value="Georgia" >Georgia</option>
			     
					   <option value="Germany" >Germany</option>
			     
					   <option value="Ghana" >Ghana</option>
			     
					   <option value="Gibraltar" >Gibraltar</option>
			     
					   <option value="Greece" >Greece</option>

			     
					   <option value="Greenland" >Greenland</option>
			     
					   <option value="Grenada" >Grenada</option>
			     
					   <option value="Guadeloupe" >Guadeloupe</option>
			     
					   <option value="Guam" >Guam</option>
			     
					   <option value="Guatemala" >Guatemala</option>
			     
					   <option value="Guinea" >Guinea</option>

			     
					   <option value="Guinea-Bissau" >Guinea-Bissau</option>
			     
					   <option value="Guyana" >Guyana</option>
			     
					   <option value="Haiti" >Haiti</option>
			     
					   <option value="Honduras" >Honduras</option>
			     
					   <option value="Hong Kong" >Hong Kong</option>
			     
					   <option value="Hungary" >Hungary</option>

			     
					   <option value="Iceland" >Iceland</option>
			     
					   <option value="India" >India</option>
			     
					   <option value="Indonesia" >Indonesia</option>
			     
					   <option value="Iran" >Iran</option>
			     
					   <option value="Iraq" >Iraq</option>
			     
					   <option value="Ireland" >Ireland</option>

			     
					   <option value="Israel" >Israel</option>
			     
					   <option value="Italy" >Italy</option>
			     
					   <option value="Jamaica" >Jamaica</option>
			     
					   <option value="Japan" >Japan</option>
			     
					   <option value="Jordan" >Jordan</option>
			     
					   <option value="Kazakhstan" >Kazakhstan</option>

			     
					   <option value="Kenya" >Kenya</option>
			     
					   <option value="Kiribati" >Kiribati</option>
			     
					   <option value="Kuwait" >Kuwait</option>
			     
					   <option value="Kyrgyzstan" >Kyrgyzstan</option>
			     
					   <option value="Laos" >Laos</option>
			     
					   <option value="Latvia" >Latvia</option>

			     
					   <option value="Lebanon" >Lebanon</option>
			     
					   <option value="Lesotho" >Lesotho</option>
			     
					   <option value="Liberia" >Liberia</option>
			     
					   <option value="Libya" >Libya</option>
			     
					   <option value="Liechtenstein" >Liechtenstein</option>
			     
					   <option value="Lithuania" >Lithuania</option>

			     
					   <option value="Luxembourg" >Luxembourg</option>
			     
					   <option value="Macau" >Macau</option>
			     
					   <option value="Macedonia" >Macedonia</option>
			     
					   <option value="Madagascar" >Madagascar</option>
			     
					   <option value="Malawi" >Malawi</option>
			     
					   <option value="Malaysia" >Malaysia</option>

			     
					   <option value="Maldives" >Maldives</option>
			     
					   <option value="Mali" >Mali</option>
			     
					   <option value="Malta" >Malta</option>
			     
					   <option value="Marshall Islands" >Marshall Islands</option>
			     
					   <option value="Martinique" >Martinique</option>
			     
					   <option value="Mauritania" >Mauritania</option>

			     
					   <option value="Mauritius" >Mauritius</option>
			     
					   <option value="Mayotte" >Mayotte</option>
			     
					   <option value="Mexico" >Mexico</option>
			     
					   <option value="Moldova" >Moldova</option>
			     
					   <option value="Monaco" >Monaco</option>
			     
					   <option value="Mongolia" >Mongolia</option>

			     
					   <option value="Montserrat" >Montserrat</option>
			     
					   <option value="Morocco" >Morocco</option>
			     
					   <option value="Mozambique" >Mozambique</option>
			     
					   <option value="Namibia" >Namibia</option>
			     
					   <option value="Nauru" >Nauru</option>
			     
					   <option value="Nepal" >Nepal</option>

			     
					   <option value="Netherlands" >Netherlands</option>
			     
					   <option value="Netherlands Antilles" >Netherlands Antilles</option>
			     
					   <option value="New Caledonia" >New Caledonia</option>
			     
					   <option value="New Zealand" >New Zealand</option>
			     
					   <option value="Nicaragua" >Nicaragua</option>
			     
					   <option value="Niger" >Niger</option>

			     
					   <option value="Nigeria" >Nigeria</option>
			     
					   <option value="North Korea" >North Korea</option>
			     
					   <option value="Northern Mariana Islands" >Northern Mariana Islands</option>
			     
					   <option value="Norway" >Norway</option>
			     
					   <option value="Oman" >Oman</option>
			     
					   <option value="Pakistan" >Pakistan</option>

			     
					   <option value="Palau" >Palau</option>
			     
					   <option value="Panama" >Panama</option>
			     
					   <option value="Papua New Guinea" >Papua New Guinea</option>
			     
					   <option value="Paraguay" >Paraguay</option>
			     
					   <option value="Peru" >Peru</option>
			     
					   <option value="Philippines" >Philippines</option>

			     
					   <option value="Pitcairn Islands" >Pitcairn Islands</option>
			     
					   <option value="Poland" >Poland</option>
			     
					   <option value="Portugal" >Portugal</option>
			     
					   <option value="Puerto Rico" >Puerto Rico</option>
			     
					   <option value="Qatar" >Qatar</option>
			     
					   <option value="Reunion" >Reunion</option>

			     
					   <option value="Romania" >Romania</option>
			     
					   <option value="Russia" >Russia</option>
			     
					   <option value="Rwanda" >Rwanda</option>
			     
					   <option value="Saint Kitts and Nevis" >Saint Kitts and Nevis</option>
			     
					   <option value="Saint Lucia" >Saint Lucia</option>
			     
					   <option value="Saint Pierre and Miquelon" >Saint Pierre and Miquelon</option>

			     
					   <option value="Saint Vincent and the Grenadines" >Saint Vincent and the Grenadines</option>
			     
					   <option value="Samoa" >Samoa</option>
			     
					   <option value="San Marino" >San Marino</option>
			     
					   <option value="Sao Tome and Principe" >Sao Tome and Principe</option>
			     
					   <option value="Saudi Arabia" >Saudi Arabia</option>
			     
					   <option value="Senegal" >Senegal</option>

			     
					   <option value="Serbia and Montenegro (Yugoslavia)" >Serbia and Montenegro (Yugoslavia)</option>
			     
					   <option value="Seychelles" >Seychelles</option>
			     
					   <option value="Sierra Leone" >Sierra Leone</option>
			     
					   <option value="Singapore" >Singapore</option>
			     
					   <option value="Slovakia" >Slovakia</option>
			     
					   <option value="Slovenia" >Slovenia</option>

			     
					   <option value="Solomon Islands" >Solomon Islands</option>
			     
					   <option value="Somalia" >Somalia</option>
			     
					   <option value="South Africa" >South Africa</option>
			     
					   <option value="South Korea" >South Korea</option>
			     
					   <option value="Spain" >Spain</option>
			     
					   <option value="Sri Lanka" >Sri Lanka</option>

			     
					   <option value="Sudan" >Sudan</option>
			     
					   <option value="Suriname" >Suriname</option>
			     
					   <option value="Swaziland" >Swaziland</option>
			     
					   <option value="Sweden" >Sweden</option>
			     
					   <option value="Switzerland" >Switzerland</option>
			     
					   <option value="Syria" >Syria</option>

			     
					   <option value="Taiwan" >Taiwan</option>
			     
					   <option value="Tajikistan" >Tajikistan</option>
			     
					   <option value="Tanzania" >Tanzania</option>
			     
					   <option value="Thailand" >Thailand</option>
			     
					   <option value="The Gambia" >The Gambia</option>
			     
					   <option value="The Holy See" >The Holy See</option>

			     
					   <option value="Togo" >Togo</option>
			     
					   <option value="Tonga" >Tonga</option>
			     
					   <option value="Trinidad and Tobago" >Trinidad and Tobago</option>
			     
					   <option value="Tunisia" >Tunisia</option>
			     
					   <option value="Turkey" >Turkey</option>
			     
					   <option value="Turkmenistan" >Turkmenistan</option>

			     
					   <option value="Turks and Caicos Islands" >Turks and Caicos Islands</option>
			     
					   <option value="Tuvalu" >Tuvalu</option>
			     
					   <option value="Uganda" >Uganda</option>
			     
					   <option value="Ukraine" >Ukraine</option>
			     
					   <option value="United Arab Emirates" >United Arab Emirates</option>
			     
					   <option value="United Kingdom" >United Kingdom</option>

			     
					   <option value="United States" >United States</option>
			     
					   <option value="United States Virgin Islands" >United States Virgin Islands</option>
			     
					   <option value="Uruguay" >Uruguay</option>
			     
					   <option value="Uzbekistan" >Uzbekistan</option>
			     
					   <option value="Vanuatu" >Vanuatu</option>
			     
					   <option value="Venezuela" >Venezuela</option>

			     
					   <option value="Vietnam" >Vietnam</option>
			     
					   <option value="West Bank and Gaza Strip" >West Bank and Gaza Strip</option>
			     
					   <option value="Western Sahara" >Western Sahara</option>
			     
					   <option value="Yemen" >Yemen</option>
			     
					   <option value="Zambia" >Zambia</option>
			     		
		</select>	
		</td>

        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--CITY:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>City<img src="images/star.gif" width="7" height="7" hspace="5"></td>        
        <td id="tdCity">        
        
             <select name="cboCity" id="cboCity" style="width:150px;">
             	<option value="-1" selected="selected">Select</option>
                 <option value="1" >Uppsala</option>
			     
					   <option value="2" >Stockholm</option>
			     
					   <option value="3" >Umea</option>
             </select>
        
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>
        
		<!--BILLING ADDRESS:-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>

        <td>Billing Address<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtBillingAddress" id="txtBillingAddress" maxlength="150" size="50" class="BDJtextBox" style="width:80%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--CONTACT PHONE:-->
		<tr class="body">

        <td class="bodyLeft">&nbsp;</td>
        <td>Contact Phone<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtContactPhone" id="txtContactPhone" maxlength="30" size="50" class="BDJtextBox" style="width:50%;" value="" />
		</td>
        <td class="bodyRight">&nbsp;</td>
        </tr>

		<!--CONTACT EMAIL:-->

		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Contact E-Mail<img src="images/star.gif" width="7" height="7" hspace="5"></td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtEmail" id="txtEmail" maxlength="40" size="50" class="BDJtextBox" style="width:50%;" value="" />
		<span class="BDJRedArial11px">[Do not type more than 1 e-mail address.]</span>
		</td>
        <td class="bodyRight">&nbsp;</td>

        </tr>

		<!--WEBSITE ADDRESS (URL):-->
		<tr class="body">
        <td class="bodyLeft">&nbsp;</td>
        <td>Website Address (URL)</td>
        <td style="padding-bottom:2px;">
		<input type="text" name="txtURL" id="txtURL" maxlength="50" size="50" class="BDJtextBox" style="width:50%;" value="">
		</td>

        <td class="bodyRight">&nbsp;</td>
        </tr>
		
		<tr>
        <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
        <td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
        <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
        </tr>		
	</table>
	    		    
        <table width="80%" align="center" border="0" cellspacing="0" cellpadding="0" style="margin-top:2px;">

		<tr class="body">
		<td class="bodyLeft">&nbsp;</td>
		<td colspan="2" align="center" style="height:50px;">
		<input type="submit" value ="Register" name ="register" width="109" height="21">
        <input type="hidden" name="txtCity1" id="txtCity1" value="" />
        <input type="hidden" name="txtArea1" id="txtArea1" value="" />
        </td>
		<td class="bodyRight">&nbsp;</td>
		</tr>

	</table>			
	</td>
	</tr>
	
</FORM>
	<tr>
    <td height="10" align="center" valign="top" class="BDJCopyright"></td>
	</tr>	
</table>

       

        
     
            
            
            
        </div>
    </div>
			</div>
            <div id="footer-wrap">
			<div id='sys_footer' class='sys_footer'>Designed by <a href='http://www.freecsstemplates.org' target='_blank'>XXXXXXXXXXX</a></div>




            </div>
        </div>
    </body>