<title>Employer Home </title>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>
	</head>
	
        
 <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:0px; padding-right:0px;">
    
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="0px"  valign="top" style="padding-top:30px;">
    
    
	
</td>


          <td valign="top">
	   <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet4">
			<FORM name="frmJobPostingStep01" id="frmJobPostingStep01" method="post" action="SUBMIT">
				<!----------------------------------
				'READING JOB POSTING STEP 02 INPUT:
				
			
				'---------------------------------->	
				<tr>

				<td class="headLeft">&nbsp;</td>
				<td height="33" colspan="2" class="head">Search Resume:</td>
				<td class="headRight">&nbsp;</td>
				</tr>
				<!--
				JOB CATEGORY:
				-->
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>
				<td width="20%">

				
				Qualification Type:
				 		 
				
                </td>
				
                <td width="80%">
               
				<SELECT name="cboJobCategory" id="cboJobCategory" style="width:230px">
					<!--option value="-1" >Select</option-->
						
							   <!--<option value="" selected></option>-->
						 <option value='-1' Selected>Select</option>
						 
                    <option value="-10" >Others</option>
				</SELECT>
                </td>
                </tr>
                <tr class="body">

				<td class="bodyLeft">&nbsp;</td>
				<td colspan="2" align="center" style="height:50px;">
				<INPUT type="submit" name="post" value ="Search Resume"  height="21">
				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
                </FORM>
                </table>
                <br>
                <br>
                <br>
	  
            <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet1">

              <tr> 
                <td width="1" class="headLeft">&nbsp;</td>
                <td width="28" align="center" class="head">SN</td>
                <td width="90" class="head">Employee Name</td>
                <td width="5" class="head">&nbsp;<br> </td>
                <td width="60" class="head">Gender</td>
                <td width="70" align="center" class="head">Mobile</td>

                
				     <td width="70" align="center" class="head">Address</td>
                     
                <td width="40" align="center" class="head">view Qalification</td>
                <td width="50" align="center" class="head">Send email</td>
                <td width="54" align="center" class="head">Add to resume List</td>
                <td width="2" align="center" class="head">&nbsp;</td>
                <td width="2" align="center" class="head">&nbsp;</td>
                 <td width="2" align="center" class="head">&nbsp;</td>
                 <td width="2" align="center" class="head">&nbsp;</td>

                <td width="2" class="headRight">&nbsp;</td>
              </tr>
              <?php  $view = $this->viewQualification;?>
               <?php  $send = $this->sendEmail;?> 
                <?php  $addresume = $this->addresume;?> 
              
               
               <?php  $datas = $this->postjoblist;?> 
               <?php for($i = 0; $i < count($datas);$i++){ ?> 
               
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td align="center" valign="middle">&nbsp; </td>
				<td align="center" valign="middle"> <?php echo$datas[$i]->getFullName()?></td>
               
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle"><?php echo$datas[$i]->getGender()?></td>

                  <td align="center" valign="middle"><?php echo$datas[$i]->getMobile()?></td>
                  <td align="center" valign="middle"><?php echo$datas[$i]->getAddress()?></td>

				<td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?php echo$view?>/emId/<?php echo$datas[$i]->getEmployeeId()?>">View</a></td>
				 
               				 <td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?php echo$send?>/email/<?php echo$datas[$i]->getEmailAddress()?>"><?php echo$datas[$i]->getEmailAddress()?></a></td>
				 
                <td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?php echo$addresume?>/add/<?php echo$datas[$i]->getEmployeeId()?>">Add To ResumList</a></td>
				 
                <td align="center" valign="middle">-</td>
                <td align="center" valign="middle">-</td>

                <td align="center" valign="middle">-</td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
               <?php  } ?>
              <tr> 
                <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
                <td colspan="11" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"  /></td>
                <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
                
              </tr>
            </table>

		 
         	          
		 	
              
		  
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>

    <td height="50" align="center" valign="bottom" class="BDJCopyright"></td>
  </tr>
</table>

 
     