
<div id="view-content">

    <?php
        echo '<form method="post" action=""><table border="1">';
       $format = "<tr class='jobheader'><td>%s:</td><td class='jobvalue'>%s</td></tr>";

       foreach($this->jobdetail as $kjob => $vjob)
       {
           foreach($vjob as $k=>$v)
           {
                printf($format, $k, $v);
           }
       }
       echo "</table><input type ='submit' value='submit'></input></form>";

    ?>
</div>
