
<div id="view-content">
    <h1>Job Description</h1>
    <?php
        $basepath = Zend_Controller_Front::getInstance()->getBaseUrl();
        echo "<form method='post' action='$basepath/jobs/applyjob'><table border='1' cellpadding='3'>";
       $format = "<tr class='header'><td>%s:</td><td class='value'>%s</td></tr>";

       foreach($this->jobdetail as $kjob => $vjob)
       {
           foreach($vjob as $k=>$v)
           {
                printf($format, $k, $v);
           }
       }
       echo "</table>
           <input type ='submit' value='submit'></input>
           <input id='jobid' name='jobid' type ='hidden' value ='$this->jobid'>
           </form>";
    ?>
</div>
