<div class="">
                    <p class="centertext">&nbsp;Welcome to
                      <font color="#0099ff"><b><i>My Job Portal</i></b></font>, your Personalized
                      Career Management Account. This account offers you Editing,
                      Deleting, and Updating of your existing account
                      and provides you all the benefits i.e., RESUME,
                      JOB CART etc. Similarly, this offers you the opportunity
                      of sending copies of your Resume to the prospective employers,
                      or find the companies that viewed your Resume.</p>
</div>
<br><br><br><br><br><br>