<title>Employer Home </title>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>
	</head>
	<body id="sys_background">
		<div id="outer">
			<div id="sys_banner" >


				<h1><a id="sys_heading" href="./">Employer Home</a></h1>
			</div>
			<div id="menu">
				<ul class='sys_navigation'>



												<li class="first"><a href=<?php echo$this->escape($this->home)?> title="Home">Home</a></li>
                                                    	<li><a href=<?php echo$this->escape($this->postjob)?> title="Post Job">Post Job</a></li>

                                                        <li><a href=<?php echo$this->escape($this->searchcv)?> title="Search Cv">Search CV</a></li>


													<li><a href=<?php echo$this->escape($this->servicecharge)?> title="Service Charge">Service charge</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Menu">Service Benifits</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Contacts">Contacts</a></li>





													<li><a href=<?php echo$this->escape($this->contact)?> title="Other">Other</a></li>





													


													








									</ul>
			</div>
			<div id="content">
				    <div style="width: 100%; padding: 0px; margin: 0px" class="layout_1-column">

        <div id="layout_row1">
        
        
 <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:20px; padding-right:20px;"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #FFFFFF;">
        <tr>
          <td width="215" height="30" align="center"><img src="images/txt_corporate_panel.gif" width="161" height="14"></td>
          <td style="background-image:url(images/gradient_top.jpg); background-repeat:repeat-y;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="BDJCompanyName" >&nbsp;&nbsp;Company Name: <?php echo$this->escape($this->company)?></td>

                <td align="right"><img src="images/icons_logout2.gif" width="16" height="15" hspace="5" align="middle"><a href="logout.asp" class="BDJGreenArial11px"><strong>Logout</strong></a></td>
            </tr>
          </table></td>
        </tr>
      </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="215" height="515" valign="top" style="padding-top:30px;">
    
    <table width="190" border="0" cellspacing="0" cellpadding="0" id="tblSet2">
        <tr>
        <td class="headLeft"></td>
        <td class="headMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
        <td class="headRight"></td>
        </tr>
        
        <tr>
        <td class="bodyLeft"><img src="images/pix.gif" width="1" height="1" /></td>
        <td valign="top" class="body" style="padding:5px;"><span class="BDJFormTitle">Main Menu</span><br>

        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>
        
        <div class="BDJWelcomeTxt">
         <img src="images/icons_addnew.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->postform)?> class='BDJNavLink'>Post a New Job</a><br>
        <img src="images/icons_account.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->findemployer)?> class='BDJNavLink'>Edit Account Info</a><br>
        <img src="images/icons_invoice.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->create)?> class='BDJNavLink'>Payment Status</a><br>  
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->create)?> class='BDJNavLink'>Contact Support</a><br>

        <img src="images/btn_icon_login.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href=<?php echo$this->escape($this->create)?> class='BDJNavLink'>Change Password</a><br>
        
        <!--
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>                      
        <img src="images/icons_email.gif" width="15" height="16" vspace="4" align="absmiddle" style="margin-right:5px;"><br>
        -->
        

        </div>
        
        <img src="images/icons_logout.gif" width="15" height="16" vspace="4" align="middle" style="margin-right:5px;"><a href='logout.asp' class='BDJNavLink'>Logout</a><br>
        
        
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>
        <span class="BDJFormTitle">Account Status</span><br>
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"><br>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
            
            <td class="BDJGrayArial12px">Online Job Posting<br>

            <img src="images/pix.gif" width="50" height="10"><br>
            CV Database Access</td>
            
    
            <td width="30" align="right" class="BDJNoticeVerdana11Red"><strong>						
            No&nbsp;<br>
            <img src="images/pix.gif" width="30" height="10"><br>
            No&nbsp;</strong></td>
            </tr>
        </table>

        
        
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"/><br/><span class="BDJFormTitle"></span><br/>
        <img src="images/pix_gray.gif" width="100%" height="1" vspace="6"/>
       
       
        <br/>
        <span class="BDJtabLinkSelected"></span> <br/><span class="BDJGrayArial12px"><strong></strong></span>
        <div  style="margin-top:5px;" align="justify" class="BDJRedArial11px"></div>
        <div class="BDJWelcomeTxt"></div>

        </td>    
        <td class="bodyRight"><img src="images/pix.gif" width="1" height="1" /></td>
        </tr>
        
        <tr>
        <td class="footerLeft"></td>
        <td class="footerMiddle"><img src="images/pix.gif" width="100%" height="1" /></td>
        <td class="footerRight"></td>
        </tr>    
    </table>
	<script type="text/JavaScript">qm_create(0,true)</script>

</td>


          <td valign="top">
	   <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet4">
			<FORM name="frmJobPostingStep01" id="frmJobPostingStep01" method="post" action="SUBMIT">
				<!----------------------------------
				'READING JOB POSTING STEP 02 INPUT:
				
			
				'---------------------------------->	
				<tr>

				<td class="headLeft">&nbsp;</td>
				<td height="33" colspan="2" class="head">Search Resume:</td>
				<td class="headRight">&nbsp;</td>
				</tr>
				<!--
				JOB CATEGORY:
				-->
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>
				<td width="30%">

				
				Qualification Type:
				 		 
				
                </td>
				
                <td width="70%">
               
				<SELECT name="cboJobCategory" id="cboJobCategory" style="width:230px">
					<!--option value="-1" >Select</option-->
						
							   <!--<option value="" selected></option>-->
						 <option value='-1' Selected>Select</option>
						 
                    <option value="-10" >Others</option>
				</SELECT>
                </td>
                </tr>
                <tr class="body">

				<td class="bodyLeft">&nbsp;</td>
				<td colspan="2" align="center" style="height:50px;">
				<INPUT type="submit" name="post" value ="Search Resume" width="109" height="21">
				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
                </FORM>
                </table>
                <br>
                <br>
                <br>
	  
            <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet1">

              <tr> 
                <td width="6" class="headLeft">&nbsp;</td>
                <td width="28" align="center" class="head">SN</td>
                <td width="90" class="head">Employee Name</td>
                <td width="5" class="head">&nbsp;<br> </td>
                <td width="60" class="head">Gender</td>
                <td width="70" align="center" class="head">Mobile</td>

                
				     <td width="70" align="center" class="head">Address</td>
                     
                <td width="40" align="center" class="head">view Qalification</td>
                <td width="90" align="center" class="head">Send email</td>
                <td width="54" align="center" class="head">Add to resume List</td>
                <td width="40" align="center" class="head">&nbsp;</td>
                <td width="50" align="center" class="head">&nbsp;</td>
                 <td width="50" align="center" class="head">&nbsp;</td>
                 <td width="50" align="center" class="head">&nbsp;</td>

                <td width="90" class="headRight">&nbsp;</td>
              </tr>
              <?php  $view = $this->viewQualification;?>
               <?php  $send = $this->sendEmail;?> 
                <?php  $addresume = $this->addresume;?> 
              
               
               <?php  $datas = $this->postjoblist;?> 
               <?php for($i = 0; $i < count($datas);$i++){ ?> 
               
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td align="center" valign="middle">&nbsp; </td>
				<td align="center" valign="middle"> <?php echo$datas[$i]->getFullName()?></td>
               
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle"><?php echo$datas[$i]->getGender()?></td>

                  <td align="center" valign="middle"><?php echo$datas[$i]->getMobile()?></td>
                  <td align="center" valign="middle"><?php echo$datas[$i]->getAddress()?></td>

				<td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?php echo$view?>/emId/<?php echo$datas[$i]->getEmployeeId()?>">View</a></td>
				 
               				 <td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?php echo$send?>/email/<?php echo$datas[$i]->getEmailAddress()?>"><?php echo$datas[$i]->getEmailAddress()?></a></td>
				 
                <td align="center" valign="middle" nowrap="nowrap" class="bodyCell"><a href="<?php echo$addresume?>/add/<?php echo$datas[$i]->getEmployeeId()?>">Add To ResumList</a></td>
				 
                <td align="center" valign="middle">-</td>
                <td align="center" valign="middle">-</td>

                <td align="center" valign="middle">-</td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
               <?php  } ?>
              <tr> 
                <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
                <td colspan="11" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"  /></td>
                <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
                
              </tr>
            </table>

		 
         <div class="BDJInstruction2">
			<strong><u></u></strong>
<br/>
<br/>
            <br/>
           </div>	          
		 	
              
		  
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>

    <td height="50" align="center" valign="bottom" class="BDJCopyright"></td>
  </tr>
</table>

 
       

        
     
            
            
            
        </div>
    </div>
			</div>
            <div id="footer-wrap">
			<div id='sys_footer' class='sys_footer'>Designed by <a href='http://www.freecsstemplates.org' target='_blank'>XXXXXXXXXXX</a></div>




            </div>
        </div>
    </body>