
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>
<title>Employer Home </title>


	</head>
	
        
     <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
	<tr>
    <td style="padding-left:20px; padding-right:20px;">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #FFFFFF;">
        <tr>

        <td width="215" height="30" align="center"><img src="images/txt_corporate_panel.gif" width="161" height="14"></td>
        <td style="background-image:url(images/gradient_top.jpg); background-repeat:repeat-y;">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
        	<tr>
        	<td class="BDJCompanyName">&nbsp;&nbsp;Company Name: INSA</td>
              </tr>
        </table>

		</td>
        </tr>
    </table>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
        <td width="215" valign="top" style="padding-top:30px;">
            
 

        <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet4">
			<FORM name="frmJobPostingStep01" id="frmJobPostingStep01" method="post" action=<?php echo$this->escape($this->sendtoEmployee)?>>
			
				<tr>

				<td class="headLeft">&nbsp;</td>
				<td height="33" colspan="2" class="head">Send Email to Employee:</td>
				<td class="headRight">&nbsp;</td>
				</tr>
			
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>
				<td>

				
					 Email to:
						 
				<img src="images/star.gif" width="7" height="7" hspace="5">				</td>
				<td>
				<INPUT type="text" name="txtToEmail" id="txtToEmail" class="BDJtextBox" style="width:90%;" maxlength="100" value=<?php echo$this->escape($this->emailId)?>>				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
				<!--
	
				-->            			
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>

				<td>
				
				     Email From:
						 
				<img src="images/star.gif" width="7" height="7" hspace="5">				</td>
				<td>
				<INPUT name="taxtEmailFrom" type="text" class="BDJtextBox" id="taxtEmailFrom" style="width:90%;" value=""  maxlength="100">				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
				
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>

				<td>
				
				     Subject:
						 
				<img src="images/star.gif" width="7" height="7" hspace="5">				</td>
				<td>
				<INPUT name="taxtSubject" type="text" class="BDJtextBox" id="taxtSubject" style="width:90%;" value=""  maxlength="100">				</td>
				<td class="bodyRight">&nbsp;</td>
				</tr>
				<tr class="body">
				<td class="bodyLeft">&nbsp;</td>

				<td>
				
				     Body:
						 
				<img src="images/star.gif" width="7" height="7" hspace="5">				</td>
				<td>
						<TEXTAREA name="txtbody" id="txtbody"  class="BDJtextBox" style="width:100%; height:80px;"> </TEXTAREA></td>
			<td class="bodyRight">&nbsp;</td>
				</tr>
				    	
	    						
			
							
				<!--END-->  
				<tr class="body">

				<td class="bodyLeft">&nbsp;</td>
				<td colspan="2" align="center" style="height:50px;">
				<INPUT type="submit" name="post" value ="Send" width="109" height="21">
				
				<td class="bodyRight">&nbsp;</td>
				</tr>
				
				<tr>
				<td class="footerLeft"><img src="images/pix.gif" width="6" height="5"/></td>
				<td colspan="2" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"/></td>
				<td class="footerRight"><img src="images/pix.gif" width="6" height="5"/></td>

				</tr>
			</FORM>
        </table>

        </td>
        </tr>
        </table>
        </td>
        </tr>
        </table>
        
     
            
            