<title>Employer Home </title>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/EmployerCSS.css'); ?>
	</head>
	
        
        
 <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="BDJPageBorder">
  <tr>
    <td style="padding-left:0px; padding-right:0px;"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #FFFFFF;">
        <tr>
          <td width="215" height="30" align="center"><img src="images/txt_corporate_panel.gif" width="161" height="14"></td>
          <td style="background-image:url(images/gradient_top.jpg); background-repeat:repeat-y;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="BDJCompanyName" >&nbsp;&nbsp;Company Name: <?php echo$this->escape($this->company)?></td>

              
            </tr>
          </table></td>
        </tr>
      </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="0" valign="top" style="padding-top:30px;">
    
    

</td>


          <td valign="top">
	   
	  
           

		 <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tblSet1">

              <tr> 
                <td width="6" class="headLeft">&nbsp;</td>
                <td width="28" align="center" class="head">SN</td>
                <td width="90" class="head">Qualification Id</td>
                <td width="5" class="head">&nbsp;<br> </td>
                <td width="90" class="head">Qualification Type</td>
                <td width="90" align="center" class="head">Date From</td>

                
				     <td width="90" align="center" class="head">Date To</td>
                     
                <td width="90" align="center" class="head">Organization Name</td>
                <td width="100" align="center" class="head">Organization Address</td>
                <td width="2" align="center" class="head">&nbsp;</td>
                <td width="2" align="center" class="head">&nbsp;</td>
                <td width="2" align="center" class="head">&nbsp;</td>
                 <td width="2" align="center" class="head">&nbsp;</td>
                <td width="2" class="headRight">&nbsp;</td>
              </tr>
               
               <?php  $datas = $this->qalification;?> 
               <?php for($i = 0; $i < count($datas);$i++){ ?> 
               
               
               
               
              <tr class="body"> 
                <td class="bodyLeft">&nbsp;</td>
                <td align="center" valign="middle">&nbsp; </td>
				<td align="center" valign="middle"> <?php echo$datas[$i]->getQualificattionId()?></td>
               
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle"><?php echo$datas[$i]->getQualificationType()?></td>

                  <td align="center" valign="middle"><?php echo$datas[$i]->getFromDate()?></td>
                  <td align="center" valign="middle"><?php echo$datas[$i]->getToDate()?></td>

				<td align="center" valign="middle" ><?php echo$datas[$i]->getOrganization()?></td>
				 
               <td align="center" valign="middle"><?php echo$datas[$i]->getLocation()?></td>
				 
                <td align="center" valign="middle" >&nbsp;</td>
				 
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle">&nbsp;</td>

                <td align="center" valign="middle">&nbsp;</td>
                <td class="bodyRight">&nbsp;</td>
              </tr>
               <?php  } ?>
              <tr> 
                <td class="footerLeft"><img src="images/pix.gif" width="6" height="5" /></td>
                <td colspan="11" class="footerMiddle"><img src="images/pix.gif" width="1" height="1"  /></td>
                <td class="footerRight"><img src="images/pix.gif" width="6" height="5" /></td>
              </tr>
            </table>
         <div class="BDJInstruction2">
			<strong><u></u></strong>
<br/>
<br/>
            <br/>
           </div>	          
		 	
              
		  
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>

    <td height="50" align="center" valign="bottom" class="BDJCopyright"></td>
  </tr>
</table>

 
       

        
     
   